// Code generated by ent, DO NOT EDIT.

package mailkeyslot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the mailkeyslot type in the database.
	Label = "mail_key_slot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlotType holds the string denoting the slot_type field in the database.
	FieldSlotType = "slot_type"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldWrappedKey holds the string denoting the wrapped_key field in the database.
	FieldWrappedKey = "wrapped_key"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldKdfSalt holds the string denoting the kdf_salt field in the database.
	FieldKdfSalt = "kdf_salt"
	// FieldPrfSalt holds the string denoting the prf_salt field in the database.
	FieldPrfSalt = "prf_salt"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the mailkeyslot in the database.
	Table = "mail_key_slots"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "mail_key_slots"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_mail_key_slots"
)

// Columns holds all SQL columns for mailkeyslot fields.
var Columns = []string{
	FieldID,
	FieldSlotType,
	FieldLabel,
	FieldVersion,
	FieldWrappedKey,
	FieldNonce,
	FieldKdfSalt,
	FieldPrfSalt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "mail_key_slots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_mail_key_slots",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// SlotType defines the type for the "slot_type" enum field.
type SlotType string

// SlotType values.
const (
	SlotTypePassword     SlotType = "password"
	SlotTypeRecoveryCode SlotType = "recovery_code"
	SlotTypeAppPassword  SlotType = "app_password"
	SlotTypePasskeyPrf   SlotType = "passkey_prf"
)

func (st SlotType) String() string {
	return string(st)
}

// SlotTypeValidator is a validator for the "slot_type" field enum values. It is called by the builders before save.
func SlotTypeValidator(st SlotType) error {
	switch st {
	case SlotTypePassword, SlotTypeRecoveryCode, SlotTypeAppPassword, SlotTypePasskeyPrf:
		return nil
	default:
		return fmt.Errorf("mailkeyslot: invalid enum value for slot_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the MailKeySlot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlotType orders the results by the slot_type field.
func BySlotType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlotType, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
