// Code generated by ent, DO NOT EDIT.

package encryptionsetup

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the encryptionsetup type in the database.
	Label = "encryption_setup"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldPrepared holds the string denoting the prepared field in the database.
	FieldPrepared = "prepared"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the encryptionsetup in the database.
	Table = "encryption_setups"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "encryption_setups"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_encryption_setups"
)

// Columns holds all SQL columns for encryptionsetup fields.
var Columns = []string{
	FieldID,
	FieldMode,
	FieldPrepared,
	FieldAttempts,
	FieldExpiresAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "encryption_setups"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_encryption_setups",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// PreparedValidator is a validator for the "prepared" field. It is called by the builders before save.
	PreparedValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
)

// Mode defines the type for the "mode" enum field.
type Mode string

// Mode values.
const (
	ModeSetup    Mode = "setup"
	ModeRotation Mode = "rotation"
)

func (m Mode) String() string {
	return string(m)
}

// ModeValidator is a validator for the "mode" field enum values. It is called by the builders before save.
func ModeValidator(m Mode) error {
	switch m {
	case ModeSetup, ModeRotation:
		return nil
	default:
		return fmt.Errorf("encryptionsetup: invalid enum value for mode field: %q", m)
	}
}

// OrderOption defines the ordering options for the EncryptionSetup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByPrepared orders the results by the prepared field.
func ByPrepared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrepared, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
