// Code generated by ent, DO NOT EDIT.

package webdomain

import (
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldLTE(FieldID, id))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldDomain, v))
}

// ServeStatic applies equality check predicate on the "serve_static" field. It's identical to ServeStaticEQ.
func ServeStatic(v bool) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldServeStatic, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldContainsFold(FieldDomain, v))
}

// HstsEQ applies the EQ predicate on the "hsts" field.
func HstsEQ(v Hsts) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldHsts, v))
}

// HstsNEQ applies the NEQ predicate on the "hsts" field.
func HstsNEQ(v Hsts) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNEQ(FieldHsts, v))
}

// HstsIn applies the In predicate on the "hsts" field.
func HstsIn(vs ...Hsts) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldIn(FieldHsts, vs...))
}

// HstsNotIn applies the NotIn predicate on the "hsts" field.
func HstsNotIn(vs ...Hsts) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNotIn(FieldHsts, vs...))
}

// ServeStaticEQ applies the EQ predicate on the "serve_static" field.
func ServeStaticEQ(v bool) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldServeStatic, v))
}

// ServeStaticNEQ applies the NEQ predicate on the "serve_static" field.
func ServeStaticNEQ(v bool) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNEQ(FieldServeStatic, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebDomain {
	return predicate.WebDomain(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRules applies the HasEdge predicate on the "rules" edge.
func HasRules() predicate.WebDomain {
	return predicate.WebDomain(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RulesTable, RulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRulesWith applies the HasEdge predicate on the "rules" edge with a given conditions (other predicates).
func HasRulesWith(preds ...predicate.WebRule) predicate.WebDomain {
	return predicate.WebDomain(func(s *sql.Selector) {
		step := newRulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.WebDomain {
	return predicate.WebDomain(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.WebDomain {
	return predicate.WebDomain(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebDomain) predicate.WebDomain {
	return predicate.WebDomain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebDomain) predicate.WebDomain {
	return predicate.WebDomain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebDomain) predicate.WebDomain {
	return predicate.WebDomain(sql.NotPredicates(p))
}
