// Code generated by ent, DO NOT EDIT.

package zoneserial

import (
	"naust/daemon/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLTE(FieldID, id))
}

// Zone applies equality check predicate on the "zone" field. It's identical to ZoneEQ.
func Zone(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldZone, v))
}

// Serial applies equality check predicate on the "serial" field. It's identical to SerialEQ.
func Serial(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldSerial, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldContentHash, v))
}

// ZoneEQ applies the EQ predicate on the "zone" field.
func ZoneEQ(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldZone, v))
}

// ZoneNEQ applies the NEQ predicate on the "zone" field.
func ZoneNEQ(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNEQ(FieldZone, v))
}

// ZoneIn applies the In predicate on the "zone" field.
func ZoneIn(vs ...string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldIn(FieldZone, vs...))
}

// ZoneNotIn applies the NotIn predicate on the "zone" field.
func ZoneNotIn(vs ...string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNotIn(FieldZone, vs...))
}

// ZoneGT applies the GT predicate on the "zone" field.
func ZoneGT(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGT(FieldZone, v))
}

// ZoneGTE applies the GTE predicate on the "zone" field.
func ZoneGTE(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGTE(FieldZone, v))
}

// ZoneLT applies the LT predicate on the "zone" field.
func ZoneLT(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLT(FieldZone, v))
}

// ZoneLTE applies the LTE predicate on the "zone" field.
func ZoneLTE(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLTE(FieldZone, v))
}

// ZoneContains applies the Contains predicate on the "zone" field.
func ZoneContains(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldContains(FieldZone, v))
}

// ZoneHasPrefix applies the HasPrefix predicate on the "zone" field.
func ZoneHasPrefix(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldHasPrefix(FieldZone, v))
}

// ZoneHasSuffix applies the HasSuffix predicate on the "zone" field.
func ZoneHasSuffix(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldHasSuffix(FieldZone, v))
}

// ZoneEqualFold applies the EqualFold predicate on the "zone" field.
func ZoneEqualFold(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEqualFold(FieldZone, v))
}

// ZoneContainsFold applies the ContainsFold predicate on the "zone" field.
func ZoneContainsFold(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldContainsFold(FieldZone, v))
}

// SerialEQ applies the EQ predicate on the "serial" field.
func SerialEQ(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldSerial, v))
}

// SerialNEQ applies the NEQ predicate on the "serial" field.
func SerialNEQ(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNEQ(FieldSerial, v))
}

// SerialIn applies the In predicate on the "serial" field.
func SerialIn(vs ...int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldIn(FieldSerial, vs...))
}

// SerialNotIn applies the NotIn predicate on the "serial" field.
func SerialNotIn(vs ...int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNotIn(FieldSerial, vs...))
}

// SerialGT applies the GT predicate on the "serial" field.
func SerialGT(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGT(FieldSerial, v))
}

// SerialGTE applies the GTE predicate on the "serial" field.
func SerialGTE(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGTE(FieldSerial, v))
}

// SerialLT applies the LT predicate on the "serial" field.
func SerialLT(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLT(FieldSerial, v))
}

// SerialLTE applies the LTE predicate on the "serial" field.
func SerialLTE(v int64) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLTE(FieldSerial, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.FieldContainsFold(FieldContentHash, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ZoneSerial) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ZoneSerial) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ZoneSerial) predicate.ZoneSerial {
	return predicate.ZoneSerial(sql.NotPredicates(p))
}
