// Code generated by ent, DO NOT EDIT.

package zoneserial

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the zoneserial type in the database.
	Label = "zone_serial"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldZone holds the string denoting the zone field in the database.
	FieldZone = "zone"
	// FieldSerial holds the string denoting the serial field in the database.
	FieldSerial = "serial"
	// FieldContentHash holds the string denoting the content_hash field in the database.
	FieldContentHash = "content_hash"
	// Table holds the table name of the zoneserial in the database.
	Table = "zone_serials"
)

// Columns holds all SQL columns for zoneserial fields.
var Columns = []string{
	FieldID,
	FieldZone,
	FieldSerial,
	FieldContentHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ZoneValidator is a validator for the "zone" field. It is called by the builders before save.
	ZoneValidator func(string) error
	// SerialValidator is a validator for the "serial" field. It is called by the builders before save.
	SerialValidator func(int64) error
	// ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	ContentHashValidator func(string) error
)

// OrderOption defines the ordering options for the ZoneSerial queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByZone orders the results by the zone field.
func ByZone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZone, opts...).ToFunc()
}

// BySerial orders the results by the serial field.
func BySerial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSerial, opts...).ToFunc()
}

// ByContentHash orders the results by the content_hash field.
func ByContentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentHash, opts...).ToFunc()
}
