// Package apigen generates the TypeScript side of the wire contract
// from the Go structs in internal/api. The generated file is checked
// into the frontend and a drift test regenerates it on every test run,
// so the two sides cannot silently diverge.
//
// Mapping rules (the honest wire contract, not the convenient one):
//   - time.Time marshals as an RFC 3339 string, so it maps to string.
//   - json.RawMessage is arbitrary JSON, so it maps to unknown.
//   - A field with omitempty becomes optional (absent, never null).
//   - A pointer, slice, or map WITHOUT omitempty maps to T | null,
//     because encoding/json emits null for the nil value. The union
//     forces the frontend to handle it at compile time.
package apigen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"reflect"
	"sort"
	"strings"
)

// Generate parses the Go package at pkgDir and returns the TypeScript
// source for every exported struct type, in source order.
func Generate(pkgDir string) ([]byte, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, pkgDir, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", pkgDir, err)
	}
	var files []*ast.File
	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.Name, "_test") {
			continue
		}
		names := make([]string, 0, len(pkg.Files))
		for name := range pkg.Files {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			files = append(files, pkg.Files[name])
		}
	}

	// First pass: collect declared type names so field types can be
	// checked against them (an unknown name is a generator bug, and
	// failing loudly beats emitting any).
	declared := map[string]bool{}
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if ts.Name.IsExported() {
					declared[ts.Name.Name] = true
				}
			}
		}
	}

	var b strings.Builder
	b.WriteString(header)
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if !ts.Name.IsExported() {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return nil, fmt.Errorf("%s: only struct types are supported", ts.Name.Name)
				}
				// The doc comment sits on the GenDecl for single-spec
				// declarations (the usual form).
				doc := ts.Doc
				if doc == nil {
					doc = gd.Doc
				}
				if err := writeType(&b, ts.Name.Name, doc, st, declared); err != nil {
					return nil, err
				}
			}
		}
	}
	return []byte(b.String()), nil
}

const header = `// GENERATED by apigen from daemon/internal/api. DO NOT EDIT.
// Regenerate: cd daemon && go generate ./internal/api
`

func writeType(b *strings.Builder, name string, doc *ast.CommentGroup, st *ast.StructType, declared map[string]bool) error {
	b.WriteString("\n")
	writeJSDoc(b, doc, "")
	fmt.Fprintf(b, "export type %s = {\n", name)
	for _, field := range st.Fields.List {
		if len(field.Names) != 1 {
			return fmt.Errorf("%s: embedded or multi-name fields are not supported", name)
		}
		fieldName := field.Names[0].Name
		jsonName, omitempty, skip, err := jsonTag(field, fieldName)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", name, fieldName, err)
		}
		if skip {
			continue
		}
		tsType, nullable, err := tsType(field.Type, declared)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", name, fieldName, err)
		}
		writeJSDoc(b, fieldDoc(field), "  ")
		opt, null := "", ""
		if omitempty {
			// Omitted when empty: absent, never null on the wire.
			opt = "?"
		} else if nullable {
			null = " | null"
		}
		fmt.Fprintf(b, "  %s%s: %s%s\n", jsonName, opt, tsType, null)
	}
	b.WriteString("}\n")
	return nil
}

// fieldDoc prefers the leading doc comment and falls back to a
// same-line trailing comment (used for short value enumerations).
func fieldDoc(field *ast.Field) *ast.CommentGroup {
	if field.Doc != nil {
		return field.Doc
	}
	return field.Comment
}

func writeJSDoc(b *strings.Builder, doc *ast.CommentGroup, indent string) {
	if doc == nil {
		return
	}
	var lines []string
	for _, c := range doc.List {
		text := strings.TrimPrefix(c.Text, "//")
		text = strings.TrimPrefix(text, " ")
		lines = append(lines, text)
	}
	if len(lines) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(b, "%s/**\n", indent)
	for _, line := range lines {
		fmt.Fprintf(b, "%s * %s\n", indent, strings.TrimRight(line, " "))
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

func jsonTag(field *ast.Field, goName string) (name string, omitempty, skip bool, err error) {
	if field.Tag == nil {
		return "", false, false, fmt.Errorf("missing json tag")
	}
	tag := reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("json")
	if tag == "" {
		return "", false, false, fmt.Errorf("missing json tag")
	}
	parts := strings.Split(tag, ",")
	if parts[0] == "-" {
		return "", false, true, nil
	}
	if parts[0] == "" {
		return "", false, false, fmt.Errorf("json tag must name the field explicitly")
	}
	for _, opt := range parts[1:] {
		if opt == "omitempty" {
			omitempty = true
		}
	}
	return parts[0], omitempty, false, nil
}

// tsType maps a Go type expression to its TypeScript form. nullable
// reports whether the Go zero value marshals to JSON null (pointers,
// slices, maps), which the caller turns into an optional marker or a
// null union depending on omitempty.
func tsType(expr ast.Expr, declared map[string]bool) (ts string, nullable bool, err error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", false, nil
		case "bool":
			return "boolean", false, nil
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			return "number", false, nil
		default:
			if declared[t.Name] {
				return t.Name, false, nil
			}
			return "", false, fmt.Errorf("unsupported type %s", t.Name)
		}
	case *ast.SelectorExpr:
		pkg, ok := t.X.(*ast.Ident)
		if !ok {
			return "", false, fmt.Errorf("unsupported selector type")
		}
		switch pkg.Name + "." + t.Sel.Name {
		case "time.Time":
			// encoding/json marshals time.Time as an RFC 3339 string.
			return "string", false, nil
		case "json.RawMessage":
			return "unknown", false, nil
		default:
			return "", false, fmt.Errorf("unsupported type %s.%s", pkg.Name, t.Sel.Name)
		}
	case *ast.StarExpr:
		inner, _, err := tsType(t.X, declared)
		if err != nil {
			return "", false, err
		}
		return inner, true, nil
	case *ast.ArrayType:
		if t.Len != nil {
			return "", false, fmt.Errorf("fixed-size arrays are not supported")
		}
		inner, _, err := tsType(t.Elt, declared)
		if err != nil {
			return "", false, err
		}
		if strings.Contains(inner, " ") {
			inner = "(" + inner + ")"
		}
		return inner + "[]", true, nil
	case *ast.MapType:
		key, ok := t.Key.(*ast.Ident)
		if !ok || key.Name != "string" {
			return "", false, fmt.Errorf("only string map keys are supported")
		}
		inner, _, err := tsType(t.Value, declared)
		if err != nil {
			return "", false, err
		}
		return "Record<string, " + inner + ">", true, nil
	default:
		return "", false, fmt.Errorf("unsupported type expression %T", expr)
	}
}
