// Code generated by ent, DO NOT EDIT.

package tenant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tenant type in the database.
	Label = "tenant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeAliases holds the string denoting the aliases edge name in mutations.
	EdgeAliases = "aliases"
	// EdgeWebDomains holds the string denoting the web_domains edge name in mutations.
	EdgeWebDomains = "web_domains"
	// EdgeDNSRecords holds the string denoting the dns_records edge name in mutations.
	EdgeDNSRecords = "dns_records"
	// EdgeDNSZoneProviders holds the string denoting the dns_zone_providers edge name in mutations.
	EdgeDNSZoneProviders = "dns_zone_providers"
	// Table holds the table name of the tenant in the database.
	Table = "tenants"
	// UsersTable is the table that holds the users relation/edge.
	UsersTable = "users"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the users relation/edge.
	UsersColumn = "tenant_users"
	// AliasesTable is the table that holds the aliases relation/edge.
	AliasesTable = "alias"
	// AliasesInverseTable is the table name for the Alias entity.
	// It exists in this package in order to avoid circular dependency with the "alias" package.
	AliasesInverseTable = "alias"
	// AliasesColumn is the table column denoting the aliases relation/edge.
	AliasesColumn = "tenant_aliases"
	// WebDomainsTable is the table that holds the web_domains relation/edge.
	WebDomainsTable = "web_domains"
	// WebDomainsInverseTable is the table name for the WebDomain entity.
	// It exists in this package in order to avoid circular dependency with the "webdomain" package.
	WebDomainsInverseTable = "web_domains"
	// WebDomainsColumn is the table column denoting the web_domains relation/edge.
	WebDomainsColumn = "tenant_web_domains"
	// DNSRecordsTable is the table that holds the dns_records relation/edge.
	DNSRecordsTable = "dns_records"
	// DNSRecordsInverseTable is the table name for the DNSRecord entity.
	// It exists in this package in order to avoid circular dependency with the "dnsrecord" package.
	DNSRecordsInverseTable = "dns_records"
	// DNSRecordsColumn is the table column denoting the dns_records relation/edge.
	DNSRecordsColumn = "tenant_dns_records"
	// DNSZoneProvidersTable is the table that holds the dns_zone_providers relation/edge.
	DNSZoneProvidersTable = "dns_zone_providers"
	// DNSZoneProvidersInverseTable is the table name for the DNSZoneProvider entity.
	// It exists in this package in order to avoid circular dependency with the "dnszoneprovider" package.
	DNSZoneProvidersInverseTable = "dns_zone_providers"
	// DNSZoneProvidersColumn is the table column denoting the dns_zone_providers relation/edge.
	DNSZoneProvidersColumn = "tenant_dns_zone_providers"
)

// Columns holds all SQL columns for tenant fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Tenant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUsersCount orders the results by users count.
func ByUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsersStep(), opts...)
	}
}

// ByUsers orders the results by users terms.
func ByUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAliasesCount orders the results by aliases count.
func ByAliasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAliasesStep(), opts...)
	}
}

// ByAliases orders the results by aliases terms.
func ByAliases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAliasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWebDomainsCount orders the results by web_domains count.
func ByWebDomainsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWebDomainsStep(), opts...)
	}
}

// ByWebDomains orders the results by web_domains terms.
func ByWebDomains(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWebDomainsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDNSRecordsCount orders the results by dns_records count.
func ByDNSRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDNSRecordsStep(), opts...)
	}
}

// ByDNSRecords orders the results by dns_records terms.
func ByDNSRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDNSRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDNSZoneProvidersCount orders the results by dns_zone_providers count.
func ByDNSZoneProvidersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDNSZoneProvidersStep(), opts...)
	}
}

// ByDNSZoneProviders orders the results by dns_zone_providers terms.
func ByDNSZoneProviders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDNSZoneProvidersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
	)
}
func newAliasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AliasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AliasesTable, AliasesColumn),
	)
}
func newWebDomainsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WebDomainsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WebDomainsTable, WebDomainsColumn),
	)
}
func newDNSRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DNSRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DNSRecordsTable, DNSRecordsColumn),
	)
}
func newDNSZoneProvidersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DNSZoneProvidersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DNSZoneProvidersTable, DNSZoneProvidersColumn),
	)
}
