quota quota {
    quota_driver = maildir
    quota_storage_grace = 10M
}

quota_status_success = DUNNO
quota_status_nouser = DUNNO
quota_status_overquota = "522 5.2.2 Mailbox is full"

service quota-status {
    executable = quota-status -p postfix
    inet_listener quota-status {
        port = 12340
    }
}
