service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0660
    user = postfix
    group = postfix
  }
  inet_listener lmtp {
    listen = 127.0.0.1
    port = 10026
  }
}

service imap-login {
  inet_listener imap {
    listen = ${IMAP_BIND}
    port = 143
    ssl = no
  }
}
protocol imap {
  mail_max_userip_connections = 40
}
protocol lmtp {
  auth_username_format = %{user | lower}
}
