sieve_redirect_envelope_from = recipient

sieve_script spam {
  sieve_script_type = before
  sieve_script_driver = file
  sieve_script_path = /etc/dovecot/sieve-spam.sieve
  sieve_script_precedence = 10
}

sieve_script global_before {
  sieve_script_type = before
  sieve_script_driver = file
  sieve_script_path = ${STORAGE_ROOT}/mail/sieve/global_before
  sieve_script_precedence = 20
}

sieve_script global_after {
  sieve_script_type = after
  sieve_script_driver = file
  sieve_script_path = ${STORAGE_ROOT}/mail/sieve/global_after
}

sieve_script personal {
  sieve_script_type = personal
  sieve_script_driver = file
  sieve_script_path = ${STORAGE_ROOT}/mail/sieve/%{user|domain}/%{user|username}
  sieve_script_active_path = ${STORAGE_ROOT}/mail/sieve/%{user|domain}/%{user|username}.sieve
}
