// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIToken is the predicate function for apitoken builders.
type APIToken func(*sql.Selector)

// Alias is the predicate function for alias builders.
type Alias func(*sql.Selector)

// AuthFailure is the predicate function for authfailure builders.
type AuthFailure func(*sql.Selector)

// BackupRun is the predicate function for backuprun builders.
type BackupRun func(*sql.Selector)

// CheckResult is the predicate function for checkresult builders.
type CheckResult func(*sql.Selector)

// Counter is the predicate function for counter builders.
type Counter func(*sql.Selector)

// DNSRecord is the predicate function for dnsrecord builders.
type DNSRecord func(*sql.Selector)

// DNSZoneProvider is the predicate function for dnszoneprovider builders.
type DNSZoneProvider func(*sql.Selector)

// EncryptionSetup is the predicate function for encryptionsetup builders.
type EncryptionSetup func(*sql.Selector)

// Lease is the predicate function for lease builders.
type Lease func(*sql.Selector)

// MailKeySlot is the predicate function for mailkeyslot builders.
type MailKeySlot func(*sql.Selector)

// MetricSample is the predicate function for metricsample builders.
type MetricSample func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// TOTPCredential is the predicate function for totpcredential builders.
type TOTPCredential func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WebAuthnChallenge is the predicate function for webauthnchallenge builders.
type WebAuthnChallenge func(*sql.Selector)

// WebAuthnCredential is the predicate function for webauthncredential builders.
type WebAuthnCredential func(*sql.Selector)

// WebDomain is the predicate function for webdomain builders.
type WebDomain func(*sql.Selector)

// WebRule is the predicate function for webrule builders.
type WebRule func(*sql.Selector)

// ZoneSerial is the predicate function for zoneserial builders.
type ZoneSerial func(*sql.Selector)
