plugin {
    antispam_backend = pipe
    antispam_spam_pattern_ignorecase = SPAM
    antispam_trash_pattern_ignorecase = trash;Deleted *
    antispam_allow_append_to_spam = yes
    antispam_pipe_program_spam_args = /usr/local/bin/${SPAM_SCRIPT}
    antispam_pipe_program_notspam_args = /usr/local/bin/${HAM_SCRIPT}
    antispam_pipe_program = /bin/bash
}
