// Code generated by ent, DO NOT EDIT.

package metricsample

import (
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLTE(FieldID, id))
}

// Metric applies equality check predicate on the "metric" field. It's identical to MetricEQ.
func Metric(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldMetric, v))
}

// SampledAt applies equality check predicate on the "sampled_at" field. It's identical to SampledAtEQ.
func SampledAt(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldSampledAt, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldValue, v))
}

// MetricEQ applies the EQ predicate on the "metric" field.
func MetricEQ(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldMetric, v))
}

// MetricNEQ applies the NEQ predicate on the "metric" field.
func MetricNEQ(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNEQ(FieldMetric, v))
}

// MetricIn applies the In predicate on the "metric" field.
func MetricIn(vs ...string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldIn(FieldMetric, vs...))
}

// MetricNotIn applies the NotIn predicate on the "metric" field.
func MetricNotIn(vs ...string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNotIn(FieldMetric, vs...))
}

// MetricGT applies the GT predicate on the "metric" field.
func MetricGT(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGT(FieldMetric, v))
}

// MetricGTE applies the GTE predicate on the "metric" field.
func MetricGTE(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGTE(FieldMetric, v))
}

// MetricLT applies the LT predicate on the "metric" field.
func MetricLT(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLT(FieldMetric, v))
}

// MetricLTE applies the LTE predicate on the "metric" field.
func MetricLTE(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLTE(FieldMetric, v))
}

// MetricContains applies the Contains predicate on the "metric" field.
func MetricContains(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldContains(FieldMetric, v))
}

// MetricHasPrefix applies the HasPrefix predicate on the "metric" field.
func MetricHasPrefix(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldHasPrefix(FieldMetric, v))
}

// MetricHasSuffix applies the HasSuffix predicate on the "metric" field.
func MetricHasSuffix(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldHasSuffix(FieldMetric, v))
}

// MetricEqualFold applies the EqualFold predicate on the "metric" field.
func MetricEqualFold(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEqualFold(FieldMetric, v))
}

// MetricContainsFold applies the ContainsFold predicate on the "metric" field.
func MetricContainsFold(v string) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldContainsFold(FieldMetric, v))
}

// SampledAtEQ applies the EQ predicate on the "sampled_at" field.
func SampledAtEQ(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldSampledAt, v))
}

// SampledAtNEQ applies the NEQ predicate on the "sampled_at" field.
func SampledAtNEQ(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNEQ(FieldSampledAt, v))
}

// SampledAtIn applies the In predicate on the "sampled_at" field.
func SampledAtIn(vs ...time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldIn(FieldSampledAt, vs...))
}

// SampledAtNotIn applies the NotIn predicate on the "sampled_at" field.
func SampledAtNotIn(vs ...time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNotIn(FieldSampledAt, vs...))
}

// SampledAtGT applies the GT predicate on the "sampled_at" field.
func SampledAtGT(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGT(FieldSampledAt, v))
}

// SampledAtGTE applies the GTE predicate on the "sampled_at" field.
func SampledAtGTE(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGTE(FieldSampledAt, v))
}

// SampledAtLT applies the LT predicate on the "sampled_at" field.
func SampledAtLT(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLT(FieldSampledAt, v))
}

// SampledAtLTE applies the LTE predicate on the "sampled_at" field.
func SampledAtLTE(v time.Time) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLTE(FieldSampledAt, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.MetricSample {
	return predicate.MetricSample(sql.FieldLTE(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MetricSample) predicate.MetricSample {
	return predicate.MetricSample(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MetricSample) predicate.MetricSample {
	return predicate.MetricSample(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MetricSample) predicate.MetricSample {
	return predicate.MetricSample(sql.NotPredicates(p))
}
