// Code generated by ent, DO NOT EDIT.

package totpcredential

import (
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLTE(FieldID, id))
}

// Secret applies equality check predicate on the "secret" field. It's identical to SecretEQ.
func Secret(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldSecret, v))
}

// MruToken applies equality check predicate on the "mru_token" field. It's identical to MruTokenEQ.
func MruToken(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldMruToken, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// SecretEQ applies the EQ predicate on the "secret" field.
func SecretEQ(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldSecret, v))
}

// SecretNEQ applies the NEQ predicate on the "secret" field.
func SecretNEQ(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNEQ(FieldSecret, v))
}

// SecretIn applies the In predicate on the "secret" field.
func SecretIn(vs ...string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIn(FieldSecret, vs...))
}

// SecretNotIn applies the NotIn predicate on the "secret" field.
func SecretNotIn(vs ...string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotIn(FieldSecret, vs...))
}

// SecretGT applies the GT predicate on the "secret" field.
func SecretGT(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGT(FieldSecret, v))
}

// SecretGTE applies the GTE predicate on the "secret" field.
func SecretGTE(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGTE(FieldSecret, v))
}

// SecretLT applies the LT predicate on the "secret" field.
func SecretLT(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLT(FieldSecret, v))
}

// SecretLTE applies the LTE predicate on the "secret" field.
func SecretLTE(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLTE(FieldSecret, v))
}

// SecretContains applies the Contains predicate on the "secret" field.
func SecretContains(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldContains(FieldSecret, v))
}

// SecretHasPrefix applies the HasPrefix predicate on the "secret" field.
func SecretHasPrefix(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldHasPrefix(FieldSecret, v))
}

// SecretHasSuffix applies the HasSuffix predicate on the "secret" field.
func SecretHasSuffix(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldHasSuffix(FieldSecret, v))
}

// SecretEqualFold applies the EqualFold predicate on the "secret" field.
func SecretEqualFold(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEqualFold(FieldSecret, v))
}

// SecretContainsFold applies the ContainsFold predicate on the "secret" field.
func SecretContainsFold(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldContainsFold(FieldSecret, v))
}

// MruTokenEQ applies the EQ predicate on the "mru_token" field.
func MruTokenEQ(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldMruToken, v))
}

// MruTokenNEQ applies the NEQ predicate on the "mru_token" field.
func MruTokenNEQ(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNEQ(FieldMruToken, v))
}

// MruTokenIn applies the In predicate on the "mru_token" field.
func MruTokenIn(vs ...string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIn(FieldMruToken, vs...))
}

// MruTokenNotIn applies the NotIn predicate on the "mru_token" field.
func MruTokenNotIn(vs ...string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotIn(FieldMruToken, vs...))
}

// MruTokenGT applies the GT predicate on the "mru_token" field.
func MruTokenGT(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGT(FieldMruToken, v))
}

// MruTokenGTE applies the GTE predicate on the "mru_token" field.
func MruTokenGTE(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGTE(FieldMruToken, v))
}

// MruTokenLT applies the LT predicate on the "mru_token" field.
func MruTokenLT(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLT(FieldMruToken, v))
}

// MruTokenLTE applies the LTE predicate on the "mru_token" field.
func MruTokenLTE(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLTE(FieldMruToken, v))
}

// MruTokenContains applies the Contains predicate on the "mru_token" field.
func MruTokenContains(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldContains(FieldMruToken, v))
}

// MruTokenHasPrefix applies the HasPrefix predicate on the "mru_token" field.
func MruTokenHasPrefix(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldHasPrefix(FieldMruToken, v))
}

// MruTokenHasSuffix applies the HasSuffix predicate on the "mru_token" field.
func MruTokenHasSuffix(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldHasSuffix(FieldMruToken, v))
}

// MruTokenIsNil applies the IsNil predicate on the "mru_token" field.
func MruTokenIsNil() predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIsNull(FieldMruToken))
}

// MruTokenNotNil applies the NotNil predicate on the "mru_token" field.
func MruTokenNotNil() predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotNull(FieldMruToken))
}

// MruTokenEqualFold applies the EqualFold predicate on the "mru_token" field.
func MruTokenEqualFold(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEqualFold(FieldMruToken, v))
}

// MruTokenContainsFold applies the ContainsFold predicate on the "mru_token" field.
func MruTokenContainsFold(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldContainsFold(FieldMruToken, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldContainsFold(FieldLabel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TOTPCredential {
	return predicate.TOTPCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TOTPCredential {
	return predicate.TOTPCredential(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TOTPCredential) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TOTPCredential) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TOTPCredential) predicate.TOTPCredential {
	return predicate.TOTPCredential(sql.NotPredicates(p))
}
