plugin {
  sieve_before = /etc/dovecot/sieve-spam.sieve
  sieve_before2 = ${STORAGE_ROOT}/mail/sieve/global_before
  sieve_after = ${STORAGE_ROOT}/mail/sieve/global_after
  sieve = ${STORAGE_ROOT}/mail/sieve/%d/%n.sieve
  sieve_dir = ${STORAGE_ROOT}/mail/sieve/%d/%n
  sieve_redirect_envelope_from = recipient
}
