// Code generated by ent, DO NOT EDIT.

package backuprun

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the backuprun type in the database.
	Label = "backup_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTool holds the string denoting the tool field in the database.
	FieldTool = "tool"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldWarning holds the string denoting the warning field in the database.
	FieldWarning = "warning"
	// FieldStats holds the string denoting the stats field in the database.
	FieldStats = "stats"
	// Table holds the table name of the backuprun in the database.
	Table = "backup_runs"
)

// Columns holds all SQL columns for backuprun fields.
var Columns = []string{
	FieldID,
	FieldStartedAt,
	FieldFinishedAt,
	FieldStatus,
	FieldTool,
	FieldError,
	FieldWarning,
	FieldStats,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ToolValidator is a validator for the "tool" field. It is called by the builders before save.
	ToolValidator func(string) error
	// DefaultError holds the default value on creation for the "error" field.
	DefaultError string
	// DefaultWarning holds the default value on creation for the "warning" field.
	DefaultWarning string
	// DefaultStats holds the default value on creation for the "stats" field.
	DefaultStats string
)

// OrderOption defines the ordering options for the BackupRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTool orders the results by the tool field.
func ByTool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTool, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByWarning orders the results by the warning field.
func ByWarning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarning, opts...).ToFunc()
}

// ByStats orders the results by the stats field.
func ByStats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStats, opts...).ToFunc()
}
