// Code generated by ent, DO NOT EDIT.

package webauthncredential

import (
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLTE(FieldID, id))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldCredentialID, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldData, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// LastUsed applies equality check predicate on the "last_used" field. It's identical to LastUsedEQ.
func LastUsed(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldLastUsed, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...[]byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...[]byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credential_id" field.
func CredentialIDGT(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credential_id" field.
func CredentialIDGTE(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credential_id" field.
func CredentialIDLT(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credential_id" field.
func CredentialIDLTE(v []byte) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLTE(FieldCredentialID, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLTE(FieldData, v))
}

// DataContains applies the Contains predicate on the "data" field.
func DataContains(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldContains(FieldData, v))
}

// DataHasPrefix applies the HasPrefix predicate on the "data" field.
func DataHasPrefix(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldHasPrefix(FieldData, v))
}

// DataHasSuffix applies the HasSuffix predicate on the "data" field.
func DataHasSuffix(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldHasSuffix(FieldData, v))
}

// DataEqualFold applies the EqualFold predicate on the "data" field.
func DataEqualFold(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEqualFold(FieldData, v))
}

// DataContainsFold applies the ContainsFold predicate on the "data" field.
func DataContainsFold(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldContainsFold(FieldData, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldContainsFold(FieldName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// LastUsedEQ applies the EQ predicate on the "last_used" field.
func LastUsedEQ(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldEQ(FieldLastUsed, v))
}

// LastUsedNEQ applies the NEQ predicate on the "last_used" field.
func LastUsedNEQ(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNEQ(FieldLastUsed, v))
}

// LastUsedIn applies the In predicate on the "last_used" field.
func LastUsedIn(vs ...time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIn(FieldLastUsed, vs...))
}

// LastUsedNotIn applies the NotIn predicate on the "last_used" field.
func LastUsedNotIn(vs ...time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotIn(FieldLastUsed, vs...))
}

// LastUsedGT applies the GT predicate on the "last_used" field.
func LastUsedGT(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGT(FieldLastUsed, v))
}

// LastUsedGTE applies the GTE predicate on the "last_used" field.
func LastUsedGTE(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldGTE(FieldLastUsed, v))
}

// LastUsedLT applies the LT predicate on the "last_used" field.
func LastUsedLT(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLT(FieldLastUsed, v))
}

// LastUsedLTE applies the LTE predicate on the "last_used" field.
func LastUsedLTE(v time.Time) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldLTE(FieldLastUsed, v))
}

// LastUsedIsNil applies the IsNil predicate on the "last_used" field.
func LastUsedIsNil() predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldIsNull(FieldLastUsed))
}

// LastUsedNotNil applies the NotNil predicate on the "last_used" field.
func LastUsedNotNil() predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.FieldNotNull(FieldLastUsed))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebAuthnCredential) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebAuthnCredential) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebAuthnCredential) predicate.WebAuthnCredential {
	return predicate.WebAuthnCredential(sql.NotPredicates(p))
}
