#!/bin/bash
# rav container entrypoint.
#
# The binary and static files are already in place from the multi-stage build.
# This entrypoint only writes the runtime config and starts the server.
#
# Environment variables (from docker-compose env_file / environment):
#   PRIMARY_HOSTNAME  - used in the config
#   STORAGE_ROOT      - path to the persistent data volume
#   IMAP_HOST         - Dovecot container service name (default: mail)
#   SMTP_HOST         - Postfix container service name (default: mail)

set -euo pipefail

NAUST=/opt/naust
source "$NAUST/deploy/docker/common-entrypoint.sh"

install_systemctl_stub
write_naust_conf

export RUNTIME=docker

source /etc/naust.conf

export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8

# Ensure the rav data directory exists and is writable by www-data.
mkdir -p "$STORAGE_ROOT/rav"
chown www-data:www-data "$STORAGE_ROOT/rav"
chmod 750 "$STORAGE_ROOT/rav"

# Write the rav runtime config.  IMAP_HOST and SMTP_HOST are injected via
# the Docker Compose environment so rav connects to the mail container, not
# 127.0.0.1 (which would not be Dovecot/Postfix in this container).
IMAP_HOST="${IMAP_HOST:-mail}"
SMTP_HOST="${SMTP_HOST:-mail}"

# Trust the NAUST self-signed cert so rav (via OpenSSL) can verify Dovecot's
# certificate when connecting via IMAPS (port 993).  The cert is generated by
# ssl.sh with a SAN for the MAIL_HOST container name (e.g. "mail").
if [ -f "$STORAGE_ROOT/ssl/ssl_certificate.pem" ]; then
    cp "$STORAGE_ROOT/ssl/ssl_certificate.pem" /usr/local/share/ca-certificates/naust-selfsigned.crt
    update-ca-certificates 2>/dev/null
fi

mkdir -p /etc/rav
cat > /etc/rav/config.env << EOF
HOST=0.0.0.0
PORT=3001
IMAP_HOST=${IMAP_HOST}
IMAP_PORT=993
TLS_ENABLED=true
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=587
ALLOW_CUSTOM_MAIL_SERVERS=false
DATA_DIR=${STORAGE_ROOT}/rav
STATIC_DIR=/usr/local/share/rav/static
RUST_LOG=info,tantivy=warn,async_imap=warn
SESSION_TIMEOUT_HOURS=24
EOF
chmod 640 /etc/rav/config.env
chown root:www-data /etc/rav/config.env

echo "rav config written. Starting server..."
# Source config inside the sudo'd shell so sudo's env_reset doesn't strip vars.
exec sudo -u www-data sh -c 'set -a; . /etc/rav/config.env; exec /usr/local/bin/rav-server'
