#!/bin/bash
# Management container entrypoint.
#
# Runs helperd (root) and managerd (unprivileged naust user) under
# supervisord - the same privilege split as bare metal's
# naust-helper.service / naust-managerd.service, just inside one container.
# The legacy Flask app (management/) is retired from Docker entirely; there
# is nothing else for this container to run. First-admin creation is a
# manual operator step here too, same as bare metal:
#   docker exec <management container> boxctl bootstrap

set -euo pipefail

NAUST=/opt/naust
source "$NAUST/deploy/docker/common-entrypoint.sh"

write_naust_conf

export RUNTIME=docker

cd "$NAUST"

export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8

source /etc/naust.conf
mkdir -p "$STORAGE_ROOT"

# Symlink /etc and /var paths managerd/helperd write onto the shared storage
# volume so service containers (dns, nginx) can read the same files.
link_conf_to_storage /etc/nsd nsd
mkdir -p /etc/nsd/nsd.conf.d
link_conf_to_storage /etc/nginx/naust.d nginx/naust.d
link_conf_to_storage /var/lib/naust var-lib-naust
if [ "${SPAM_FILTER:-rspamd}" = "spamassassin" ]; then
    link_conf_to_storage /etc/opendkim opendkim
fi

# Symlink munin HTML dir so managerd can serve files generated by the munin
# container, which writes to the same storage volume path.
mkdir -p "$STORAGE_ROOT/munin/www" /var/cache/munin
ln -sfn "$STORAGE_ROOT/munin/www" /var/cache/munin/www

# Create the naust system group/user and hand over the directories managerd
# writes. Mirrors helper.py's _group() and managerd.py's _user()/_dirs() -
# bare metal does this via the component system's setup pass; this container
# has no such pass for itself, so it's done here instead.
if ! getent group naust >/dev/null 2>&1; then
    groupadd --system naust
fi
if ! id -u naust >/dev/null 2>&1; then
    useradd --system --no-create-home -g naust -d /nonexistent -s /usr/sbin/nologin naust
fi

# dovecot itself is never installed in this container - only the mail
# container has it - so there is no local "dovecot" group to join. Create
# one anyway, pinned to the same gid dovecot's Dockerfile pins its own
# group to, so materialize.go's ensureDovecotGroup (which chowns
# mail/materialized/dovecot-users to a locally-resolved "dovecot" group)
# resolves to the same numeric gid dovecot's auth process actually runs
# with. See the matching comment in deploy/docker/mail/Dockerfile.
if ! getent group dovecot >/dev/null 2>&1; then
    groupadd --system -g 8991 dovecot
fi

for group in mail dovecot opendkim www-data ssl-cert; do
    getent group "$group" >/dev/null 2>&1 && usermod -aG "$group" naust
done

for entry in \
    "$STORAGE_ROOT/control:700" \
    "$STORAGE_ROOT/mail/materialized:755" \
    "$STORAGE_ROOT/mail/relay:700" \
    "$STORAGE_ROOT/ssl:750" \
    "$STORAGE_ROOT/backup:700" \
    "$STORAGE_ROOT/dns/dnssec:700" \
    "/etc/nsd/zones:755" \
    "/etc/nsd/nsd.conf.d:755" \
    "/var/lib/naust:755" \
    "/var/lib/naust-managerd:700" \
    "/var/lib/naust-managerd/cache:700"
do
    path="${entry%:*}"
    mode="${entry##*:}"
    mkdir -p "$path"
    chmod "$mode" "$path"
    chown naust:naust "$path"
done

# Existing secrets/key material created root-owned by earlier containers
# move to the daemon that actually uses them.
for tree in "$STORAGE_ROOT/ssl" "$STORAGE_ROOT/backup" "$STORAGE_ROOT/dns/dnssec"; do
    [ -d "$tree" ] && chown -R naust:naust "$tree"
done

# Backup reads the mail store via the mail group: group execute/read bits on
# the top-level path make the tree reachable.
chmod g+rX "$STORAGE_ROOT" 2>/dev/null || true
[ -d "$STORAGE_ROOT/mail" ] && chmod g+rX "$STORAGE_ROOT/mail"
[ -d "$STORAGE_ROOT/mail/mailboxes" ] && chmod g+rX "$STORAGE_ROOT/mail/mailboxes"

# helperd's socket directory - RuntimeDirectory=naust on bare metal (systemd);
# created manually here since Docker has no systemd to do it.
mkdir -p /run/naust
chown root:naust /run/naust
chmod 0750 /run/naust

echo "Starting helperd and managerd via supervisord..."
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
