// Code generated by ent, DO NOT EDIT.

package authfailure

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the authfailure type in the database.
	Label = "auth_failure"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldAt holds the string denoting the at field in the database.
	FieldAt = "at"
	// Table holds the table name of the authfailure in the database.
	Table = "auth_failures"
)

// Columns holds all SQL columns for authfailure fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldEmail,
	FieldAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultAt holds the default value on creation for the "at" field.
	DefaultAt func() time.Time
)

// OrderOption defines the ordering options for the AuthFailure queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByAt orders the results by the at field.
func ByAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAt, opts...).ToFunc()
}
