# Fail2Ban filter Naust management daemon

[INCLUDES]

before = common.conf

[Definition]

_daemon = naust

failregex = Naust Management Daemon: Failed login attempt from ip <HOST> - timestamp .*
ignoreregex =
