// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"naust/daemon/internal/store/ent/authfailure"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AuthFailure is the model entity for the AuthFailure schema.
type AuthFailure struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// At holds the value of the "at" field.
	At           time.Time `json:"at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthFailure) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authfailure.FieldID:
			values[i] = new(sql.NullInt64)
		case authfailure.FieldKind, authfailure.FieldEmail:
			values[i] = new(sql.NullString)
		case authfailure.FieldAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthFailure fields.
func (af *AuthFailure) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authfailure.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			af.ID = int(value.Int64)
		case authfailure.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				af.Kind = value.String
			}
		case authfailure.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				af.Email = value.String
			}
		case authfailure.FieldAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field at", values[i])
			} else if value.Valid {
				af.At = value.Time
			}
		default:
			af.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthFailure.
// This includes values selected through modifiers, order, etc.
func (af *AuthFailure) Value(name string) (ent.Value, error) {
	return af.selectValues.Get(name)
}

// Update returns a builder for updating this AuthFailure.
// Note that you need to call AuthFailure.Unwrap() before calling this method if this AuthFailure
// was returned from a transaction, and the transaction was committed or rolled back.
func (af *AuthFailure) Update() *AuthFailureUpdateOne {
	return NewAuthFailureClient(af.config).UpdateOne(af)
}

// Unwrap unwraps the AuthFailure entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (af *AuthFailure) Unwrap() *AuthFailure {
	_tx, ok := af.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthFailure is not a transactional entity")
	}
	af.config.driver = _tx.drv
	return af
}

// String implements the fmt.Stringer.
func (af *AuthFailure) String() string {
	var builder strings.Builder
	builder.WriteString("AuthFailure(")
	builder.WriteString(fmt.Sprintf("id=%v, ", af.ID))
	builder.WriteString("kind=")
	builder.WriteString(af.Kind)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(af.Email)
	builder.WriteString(", ")
	builder.WriteString("at=")
	builder.WriteString(af.At.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuthFailures is a parsable slice of AuthFailure.
type AuthFailures []*AuthFailure
