// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"naust/daemon/internal/store/ent/authfailure"
	"naust/daemon/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthFailureDelete is the builder for deleting a AuthFailure entity.
type AuthFailureDelete struct {
	config
	hooks    []Hook
	mutation *AuthFailureMutation
}

// Where appends a list predicates to the AuthFailureDelete builder.
func (afd *AuthFailureDelete) Where(ps ...predicate.AuthFailure) *AuthFailureDelete {
	afd.mutation.Where(ps...)
	return afd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (afd *AuthFailureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, afd.sqlExec, afd.mutation, afd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (afd *AuthFailureDelete) ExecX(ctx context.Context) int {
	n, err := afd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (afd *AuthFailureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authfailure.Table, sqlgraph.NewFieldSpec(authfailure.FieldID, field.TypeInt))
	if ps := afd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, afd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	afd.mutation.done = true
	return affected, err
}

// AuthFailureDeleteOne is the builder for deleting a single AuthFailure entity.
type AuthFailureDeleteOne struct {
	afd *AuthFailureDelete
}

// Where appends a list predicates to the AuthFailureDelete builder.
func (afdo *AuthFailureDeleteOne) Where(ps ...predicate.AuthFailure) *AuthFailureDeleteOne {
	afdo.afd.mutation.Where(ps...)
	return afdo
}

// Exec executes the deletion query.
func (afdo *AuthFailureDeleteOne) Exec(ctx context.Context) error {
	n, err := afdo.afd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authfailure.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (afdo *AuthFailureDeleteOne) ExecX(ctx context.Context) {
	if err := afdo.Exec(ctx); err != nil {
		panic(err)
	}
}
