// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/backuprun"
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BackupRunUpdate is the builder for updating BackupRun entities.
type BackupRunUpdate struct {
	config
	hooks    []Hook
	mutation *BackupRunMutation
}

// Where appends a list predicates to the BackupRunUpdate builder.
func (bru *BackupRunUpdate) Where(ps ...predicate.BackupRun) *BackupRunUpdate {
	bru.mutation.Where(ps...)
	return bru
}

// SetStartedAt sets the "started_at" field.
func (bru *BackupRunUpdate) SetStartedAt(t time.Time) *BackupRunUpdate {
	bru.mutation.SetStartedAt(t)
	return bru
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableStartedAt(t *time.Time) *BackupRunUpdate {
	if t != nil {
		bru.SetStartedAt(*t)
	}
	return bru
}

// SetFinishedAt sets the "finished_at" field.
func (bru *BackupRunUpdate) SetFinishedAt(t time.Time) *BackupRunUpdate {
	bru.mutation.SetFinishedAt(t)
	return bru
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableFinishedAt(t *time.Time) *BackupRunUpdate {
	if t != nil {
		bru.SetFinishedAt(*t)
	}
	return bru
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (bru *BackupRunUpdate) ClearFinishedAt() *BackupRunUpdate {
	bru.mutation.ClearFinishedAt()
	return bru
}

// SetStatus sets the "status" field.
func (bru *BackupRunUpdate) SetStatus(s string) *BackupRunUpdate {
	bru.mutation.SetStatus(s)
	return bru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableStatus(s *string) *BackupRunUpdate {
	if s != nil {
		bru.SetStatus(*s)
	}
	return bru
}

// SetTool sets the "tool" field.
func (bru *BackupRunUpdate) SetTool(s string) *BackupRunUpdate {
	bru.mutation.SetTool(s)
	return bru
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableTool(s *string) *BackupRunUpdate {
	if s != nil {
		bru.SetTool(*s)
	}
	return bru
}

// SetError sets the "error" field.
func (bru *BackupRunUpdate) SetError(s string) *BackupRunUpdate {
	bru.mutation.SetError(s)
	return bru
}

// SetNillableError sets the "error" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableError(s *string) *BackupRunUpdate {
	if s != nil {
		bru.SetError(*s)
	}
	return bru
}

// SetWarning sets the "warning" field.
func (bru *BackupRunUpdate) SetWarning(s string) *BackupRunUpdate {
	bru.mutation.SetWarning(s)
	return bru
}

// SetNillableWarning sets the "warning" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableWarning(s *string) *BackupRunUpdate {
	if s != nil {
		bru.SetWarning(*s)
	}
	return bru
}

// SetStats sets the "stats" field.
func (bru *BackupRunUpdate) SetStats(s string) *BackupRunUpdate {
	bru.mutation.SetStats(s)
	return bru
}

// SetNillableStats sets the "stats" field if the given value is not nil.
func (bru *BackupRunUpdate) SetNillableStats(s *string) *BackupRunUpdate {
	if s != nil {
		bru.SetStats(*s)
	}
	return bru
}

// Mutation returns the BackupRunMutation object of the builder.
func (bru *BackupRunUpdate) Mutation() *BackupRunMutation {
	return bru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bru *BackupRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bru.sqlSave, bru.mutation, bru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bru *BackupRunUpdate) SaveX(ctx context.Context) int {
	affected, err := bru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bru *BackupRunUpdate) Exec(ctx context.Context) error {
	_, err := bru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bru *BackupRunUpdate) ExecX(ctx context.Context) {
	if err := bru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bru *BackupRunUpdate) check() error {
	if v, ok := bru.mutation.Status(); ok {
		if err := backuprun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BackupRun.status": %w`, err)}
		}
	}
	if v, ok := bru.mutation.Tool(); ok {
		if err := backuprun.ToolValidator(v); err != nil {
			return &ValidationError{Name: "tool", err: fmt.Errorf(`ent: validator failed for field "BackupRun.tool": %w`, err)}
		}
	}
	return nil
}

func (bru *BackupRunUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(backuprun.Table, backuprun.Columns, sqlgraph.NewFieldSpec(backuprun.FieldID, field.TypeInt))
	if ps := bru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bru.mutation.StartedAt(); ok {
		_spec.SetField(backuprun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := bru.mutation.FinishedAt(); ok {
		_spec.SetField(backuprun.FieldFinishedAt, field.TypeTime, value)
	}
	if bru.mutation.FinishedAtCleared() {
		_spec.ClearField(backuprun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := bru.mutation.Status(); ok {
		_spec.SetField(backuprun.FieldStatus, field.TypeString, value)
	}
	if value, ok := bru.mutation.Tool(); ok {
		_spec.SetField(backuprun.FieldTool, field.TypeString, value)
	}
	if value, ok := bru.mutation.Error(); ok {
		_spec.SetField(backuprun.FieldError, field.TypeString, value)
	}
	if value, ok := bru.mutation.Warning(); ok {
		_spec.SetField(backuprun.FieldWarning, field.TypeString, value)
	}
	if value, ok := bru.mutation.Stats(); ok {
		_spec.SetField(backuprun.FieldStats, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backuprun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bru.mutation.done = true
	return n, nil
}

// BackupRunUpdateOne is the builder for updating a single BackupRun entity.
type BackupRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupRunMutation
}

// SetStartedAt sets the "started_at" field.
func (bruo *BackupRunUpdateOne) SetStartedAt(t time.Time) *BackupRunUpdateOne {
	bruo.mutation.SetStartedAt(t)
	return bruo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableStartedAt(t *time.Time) *BackupRunUpdateOne {
	if t != nil {
		bruo.SetStartedAt(*t)
	}
	return bruo
}

// SetFinishedAt sets the "finished_at" field.
func (bruo *BackupRunUpdateOne) SetFinishedAt(t time.Time) *BackupRunUpdateOne {
	bruo.mutation.SetFinishedAt(t)
	return bruo
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableFinishedAt(t *time.Time) *BackupRunUpdateOne {
	if t != nil {
		bruo.SetFinishedAt(*t)
	}
	return bruo
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (bruo *BackupRunUpdateOne) ClearFinishedAt() *BackupRunUpdateOne {
	bruo.mutation.ClearFinishedAt()
	return bruo
}

// SetStatus sets the "status" field.
func (bruo *BackupRunUpdateOne) SetStatus(s string) *BackupRunUpdateOne {
	bruo.mutation.SetStatus(s)
	return bruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableStatus(s *string) *BackupRunUpdateOne {
	if s != nil {
		bruo.SetStatus(*s)
	}
	return bruo
}

// SetTool sets the "tool" field.
func (bruo *BackupRunUpdateOne) SetTool(s string) *BackupRunUpdateOne {
	bruo.mutation.SetTool(s)
	return bruo
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableTool(s *string) *BackupRunUpdateOne {
	if s != nil {
		bruo.SetTool(*s)
	}
	return bruo
}

// SetError sets the "error" field.
func (bruo *BackupRunUpdateOne) SetError(s string) *BackupRunUpdateOne {
	bruo.mutation.SetError(s)
	return bruo
}

// SetNillableError sets the "error" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableError(s *string) *BackupRunUpdateOne {
	if s != nil {
		bruo.SetError(*s)
	}
	return bruo
}

// SetWarning sets the "warning" field.
func (bruo *BackupRunUpdateOne) SetWarning(s string) *BackupRunUpdateOne {
	bruo.mutation.SetWarning(s)
	return bruo
}

// SetNillableWarning sets the "warning" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableWarning(s *string) *BackupRunUpdateOne {
	if s != nil {
		bruo.SetWarning(*s)
	}
	return bruo
}

// SetStats sets the "stats" field.
func (bruo *BackupRunUpdateOne) SetStats(s string) *BackupRunUpdateOne {
	bruo.mutation.SetStats(s)
	return bruo
}

// SetNillableStats sets the "stats" field if the given value is not nil.
func (bruo *BackupRunUpdateOne) SetNillableStats(s *string) *BackupRunUpdateOne {
	if s != nil {
		bruo.SetStats(*s)
	}
	return bruo
}

// Mutation returns the BackupRunMutation object of the builder.
func (bruo *BackupRunUpdateOne) Mutation() *BackupRunMutation {
	return bruo.mutation
}

// Where appends a list predicates to the BackupRunUpdate builder.
func (bruo *BackupRunUpdateOne) Where(ps ...predicate.BackupRun) *BackupRunUpdateOne {
	bruo.mutation.Where(ps...)
	return bruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bruo *BackupRunUpdateOne) Select(field string, fields ...string) *BackupRunUpdateOne {
	bruo.fields = append([]string{field}, fields...)
	return bruo
}

// Save executes the query and returns the updated BackupRun entity.
func (bruo *BackupRunUpdateOne) Save(ctx context.Context) (*BackupRun, error) {
	return withHooks(ctx, bruo.sqlSave, bruo.mutation, bruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bruo *BackupRunUpdateOne) SaveX(ctx context.Context) *BackupRun {
	node, err := bruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bruo *BackupRunUpdateOne) Exec(ctx context.Context) error {
	_, err := bruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bruo *BackupRunUpdateOne) ExecX(ctx context.Context) {
	if err := bruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bruo *BackupRunUpdateOne) check() error {
	if v, ok := bruo.mutation.Status(); ok {
		if err := backuprun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BackupRun.status": %w`, err)}
		}
	}
	if v, ok := bruo.mutation.Tool(); ok {
		if err := backuprun.ToolValidator(v); err != nil {
			return &ValidationError{Name: "tool", err: fmt.Errorf(`ent: validator failed for field "BackupRun.tool": %w`, err)}
		}
	}
	return nil
}

func (bruo *BackupRunUpdateOne) sqlSave(ctx context.Context) (_node *BackupRun, err error) {
	if err := bruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backuprun.Table, backuprun.Columns, sqlgraph.NewFieldSpec(backuprun.FieldID, field.TypeInt))
	id, ok := bruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backuprun.FieldID)
		for _, f := range fields {
			if !backuprun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backuprun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bruo.mutation.StartedAt(); ok {
		_spec.SetField(backuprun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := bruo.mutation.FinishedAt(); ok {
		_spec.SetField(backuprun.FieldFinishedAt, field.TypeTime, value)
	}
	if bruo.mutation.FinishedAtCleared() {
		_spec.ClearField(backuprun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := bruo.mutation.Status(); ok {
		_spec.SetField(backuprun.FieldStatus, field.TypeString, value)
	}
	if value, ok := bruo.mutation.Tool(); ok {
		_spec.SetField(backuprun.FieldTool, field.TypeString, value)
	}
	if value, ok := bruo.mutation.Error(); ok {
		_spec.SetField(backuprun.FieldError, field.TypeString, value)
	}
	if value, ok := bruo.mutation.Warning(); ok {
		_spec.SetField(backuprun.FieldWarning, field.TypeString, value)
	}
	if value, ok := bruo.mutation.Stats(); ok {
		_spec.SetField(backuprun.FieldStats, field.TypeString, value)
	}
	_node = &BackupRun{config: bruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backuprun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bruo.mutation.done = true
	return _node, nil
}
