// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/checkresult"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CheckResultCreate is the builder for creating a CheckResult entity.
type CheckResultCreate struct {
	config
	mutation *CheckResultMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCheck sets the "check" field.
func (crc *CheckResultCreate) SetCheck(s string) *CheckResultCreate {
	crc.mutation.SetCheck(s)
	return crc
}

// SetDomain sets the "domain" field.
func (crc *CheckResultCreate) SetDomain(s string) *CheckResultCreate {
	crc.mutation.SetDomain(s)
	return crc
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (crc *CheckResultCreate) SetNillableDomain(s *string) *CheckResultCreate {
	if s != nil {
		crc.SetDomain(*s)
	}
	return crc
}

// SetCategory sets the "category" field.
func (crc *CheckResultCreate) SetCategory(s string) *CheckResultCreate {
	crc.mutation.SetCategory(s)
	return crc
}

// SetStatus sets the "status" field.
func (crc *CheckResultCreate) SetStatus(s string) *CheckResultCreate {
	crc.mutation.SetStatus(s)
	return crc
}

// SetMessage sets the "message" field.
func (crc *CheckResultCreate) SetMessage(s string) *CheckResultCreate {
	crc.mutation.SetMessage(s)
	return crc
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (crc *CheckResultCreate) SetNillableMessage(s *string) *CheckResultCreate {
	if s != nil {
		crc.SetMessage(*s)
	}
	return crc
}

// SetSteps sets the "steps" field.
func (crc *CheckResultCreate) SetSteps(s string) *CheckResultCreate {
	crc.mutation.SetSteps(s)
	return crc
}

// SetNillableSteps sets the "steps" field if the given value is not nil.
func (crc *CheckResultCreate) SetNillableSteps(s *string) *CheckResultCreate {
	if s != nil {
		crc.SetSteps(*s)
	}
	return crc
}

// SetRanAt sets the "ran_at" field.
func (crc *CheckResultCreate) SetRanAt(t time.Time) *CheckResultCreate {
	crc.mutation.SetRanAt(t)
	return crc
}

// SetElapsedMs sets the "elapsed_ms" field.
func (crc *CheckResultCreate) SetElapsedMs(i int64) *CheckResultCreate {
	crc.mutation.SetElapsedMs(i)
	return crc
}

// SetNillableElapsedMs sets the "elapsed_ms" field if the given value is not nil.
func (crc *CheckResultCreate) SetNillableElapsedMs(i *int64) *CheckResultCreate {
	if i != nil {
		crc.SetElapsedMs(*i)
	}
	return crc
}

// SetFirstFailedAt sets the "first_failed_at" field.
func (crc *CheckResultCreate) SetFirstFailedAt(t time.Time) *CheckResultCreate {
	crc.mutation.SetFirstFailedAt(t)
	return crc
}

// SetNillableFirstFailedAt sets the "first_failed_at" field if the given value is not nil.
func (crc *CheckResultCreate) SetNillableFirstFailedAt(t *time.Time) *CheckResultCreate {
	if t != nil {
		crc.SetFirstFailedAt(*t)
	}
	return crc
}

// Mutation returns the CheckResultMutation object of the builder.
func (crc *CheckResultCreate) Mutation() *CheckResultMutation {
	return crc.mutation
}

// Save creates the CheckResult in the database.
func (crc *CheckResultCreate) Save(ctx context.Context) (*CheckResult, error) {
	crc.defaults()
	return withHooks(ctx, crc.sqlSave, crc.mutation, crc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (crc *CheckResultCreate) SaveX(ctx context.Context) *CheckResult {
	v, err := crc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crc *CheckResultCreate) Exec(ctx context.Context) error {
	_, err := crc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crc *CheckResultCreate) ExecX(ctx context.Context) {
	if err := crc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (crc *CheckResultCreate) defaults() {
	if _, ok := crc.mutation.Domain(); !ok {
		v := checkresult.DefaultDomain
		crc.mutation.SetDomain(v)
	}
	if _, ok := crc.mutation.Message(); !ok {
		v := checkresult.DefaultMessage
		crc.mutation.SetMessage(v)
	}
	if _, ok := crc.mutation.Steps(); !ok {
		v := checkresult.DefaultSteps
		crc.mutation.SetSteps(v)
	}
	if _, ok := crc.mutation.ElapsedMs(); !ok {
		v := checkresult.DefaultElapsedMs
		crc.mutation.SetElapsedMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (crc *CheckResultCreate) check() error {
	if _, ok := crc.mutation.Check(); !ok {
		return &ValidationError{Name: "check", err: errors.New(`ent: missing required field "CheckResult.check"`)}
	}
	if v, ok := crc.mutation.Check(); ok {
		if err := checkresult.CheckValidator(v); err != nil {
			return &ValidationError{Name: "check", err: fmt.Errorf(`ent: validator failed for field "CheckResult.check": %w`, err)}
		}
	}
	if _, ok := crc.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "CheckResult.domain"`)}
	}
	if _, ok := crc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "CheckResult.category"`)}
	}
	if v, ok := crc.mutation.Category(); ok {
		if err := checkresult.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CheckResult.category": %w`, err)}
		}
	}
	if _, ok := crc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CheckResult.status"`)}
	}
	if v, ok := crc.mutation.Status(); ok {
		if err := checkresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CheckResult.status": %w`, err)}
		}
	}
	if _, ok := crc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "CheckResult.message"`)}
	}
	if _, ok := crc.mutation.Steps(); !ok {
		return &ValidationError{Name: "steps", err: errors.New(`ent: missing required field "CheckResult.steps"`)}
	}
	if _, ok := crc.mutation.RanAt(); !ok {
		return &ValidationError{Name: "ran_at", err: errors.New(`ent: missing required field "CheckResult.ran_at"`)}
	}
	if _, ok := crc.mutation.ElapsedMs(); !ok {
		return &ValidationError{Name: "elapsed_ms", err: errors.New(`ent: missing required field "CheckResult.elapsed_ms"`)}
	}
	return nil
}

func (crc *CheckResultCreate) sqlSave(ctx context.Context) (*CheckResult, error) {
	if err := crc.check(); err != nil {
		return nil, err
	}
	_node, _spec := crc.createSpec()
	if err := sqlgraph.CreateNode(ctx, crc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	crc.mutation.id = &_node.ID
	crc.mutation.done = true
	return _node, nil
}

func (crc *CheckResultCreate) createSpec() (*CheckResult, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckResult{config: crc.config}
		_spec = sqlgraph.NewCreateSpec(checkresult.Table, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	)
	_spec.OnConflict = crc.conflict
	if value, ok := crc.mutation.Check(); ok {
		_spec.SetField(checkresult.FieldCheck, field.TypeString, value)
		_node.Check = value
	}
	if value, ok := crc.mutation.Domain(); ok {
		_spec.SetField(checkresult.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := crc.mutation.Category(); ok {
		_spec.SetField(checkresult.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := crc.mutation.Status(); ok {
		_spec.SetField(checkresult.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := crc.mutation.Message(); ok {
		_spec.SetField(checkresult.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := crc.mutation.Steps(); ok {
		_spec.SetField(checkresult.FieldSteps, field.TypeString, value)
		_node.Steps = value
	}
	if value, ok := crc.mutation.RanAt(); ok {
		_spec.SetField(checkresult.FieldRanAt, field.TypeTime, value)
		_node.RanAt = value
	}
	if value, ok := crc.mutation.ElapsedMs(); ok {
		_spec.SetField(checkresult.FieldElapsedMs, field.TypeInt64, value)
		_node.ElapsedMs = value
	}
	if value, ok := crc.mutation.FirstFailedAt(); ok {
		_spec.SetField(checkresult.FieldFirstFailedAt, field.TypeTime, value)
		_node.FirstFailedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckResult.Create().
//		SetCheck(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckResultUpsert) {
//			SetCheck(v+v).
//		}).
//		Exec(ctx)
func (crc *CheckResultCreate) OnConflict(opts ...sql.ConflictOption) *CheckResultUpsertOne {
	crc.conflict = opts
	return &CheckResultUpsertOne{
		create: crc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckResult.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (crc *CheckResultCreate) OnConflictColumns(columns ...string) *CheckResultUpsertOne {
	crc.conflict = append(crc.conflict, sql.ConflictColumns(columns...))
	return &CheckResultUpsertOne{
		create: crc,
	}
}

type (
	// CheckResultUpsertOne is the builder for "upsert"-ing
	//  one CheckResult node.
	CheckResultUpsertOne struct {
		create *CheckResultCreate
	}

	// CheckResultUpsert is the "OnConflict" setter.
	CheckResultUpsert struct {
		*sql.UpdateSet
	}
)

// SetCheck sets the "check" field.
func (u *CheckResultUpsert) SetCheck(v string) *CheckResultUpsert {
	u.Set(checkresult.FieldCheck, v)
	return u
}

// UpdateCheck sets the "check" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateCheck() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldCheck)
	return u
}

// SetDomain sets the "domain" field.
func (u *CheckResultUpsert) SetDomain(v string) *CheckResultUpsert {
	u.Set(checkresult.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateDomain() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldDomain)
	return u
}

// SetCategory sets the "category" field.
func (u *CheckResultUpsert) SetCategory(v string) *CheckResultUpsert {
	u.Set(checkresult.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateCategory() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldCategory)
	return u
}

// SetStatus sets the "status" field.
func (u *CheckResultUpsert) SetStatus(v string) *CheckResultUpsert {
	u.Set(checkresult.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateStatus() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldStatus)
	return u
}

// SetMessage sets the "message" field.
func (u *CheckResultUpsert) SetMessage(v string) *CheckResultUpsert {
	u.Set(checkresult.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateMessage() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldMessage)
	return u
}

// SetSteps sets the "steps" field.
func (u *CheckResultUpsert) SetSteps(v string) *CheckResultUpsert {
	u.Set(checkresult.FieldSteps, v)
	return u
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateSteps() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldSteps)
	return u
}

// SetRanAt sets the "ran_at" field.
func (u *CheckResultUpsert) SetRanAt(v time.Time) *CheckResultUpsert {
	u.Set(checkresult.FieldRanAt, v)
	return u
}

// UpdateRanAt sets the "ran_at" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateRanAt() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldRanAt)
	return u
}

// SetElapsedMs sets the "elapsed_ms" field.
func (u *CheckResultUpsert) SetElapsedMs(v int64) *CheckResultUpsert {
	u.Set(checkresult.FieldElapsedMs, v)
	return u
}

// UpdateElapsedMs sets the "elapsed_ms" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateElapsedMs() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldElapsedMs)
	return u
}

// AddElapsedMs adds v to the "elapsed_ms" field.
func (u *CheckResultUpsert) AddElapsedMs(v int64) *CheckResultUpsert {
	u.Add(checkresult.FieldElapsedMs, v)
	return u
}

// SetFirstFailedAt sets the "first_failed_at" field.
func (u *CheckResultUpsert) SetFirstFailedAt(v time.Time) *CheckResultUpsert {
	u.Set(checkresult.FieldFirstFailedAt, v)
	return u
}

// UpdateFirstFailedAt sets the "first_failed_at" field to the value that was provided on create.
func (u *CheckResultUpsert) UpdateFirstFailedAt() *CheckResultUpsert {
	u.SetExcluded(checkresult.FieldFirstFailedAt)
	return u
}

// ClearFirstFailedAt clears the value of the "first_failed_at" field.
func (u *CheckResultUpsert) ClearFirstFailedAt() *CheckResultUpsert {
	u.SetNull(checkresult.FieldFirstFailedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckResult.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckResultUpsertOne) UpdateNewValues() *CheckResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckResult.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckResultUpsertOne) Ignore() *CheckResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckResultUpsertOne) DoNothing() *CheckResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckResultCreate.OnConflict
// documentation for more info.
func (u *CheckResultUpsertOne) Update(set func(*CheckResultUpsert)) *CheckResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckResultUpsert{UpdateSet: update})
	}))
	return u
}

// SetCheck sets the "check" field.
func (u *CheckResultUpsertOne) SetCheck(v string) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetCheck(v)
	})
}

// UpdateCheck sets the "check" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateCheck() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateCheck()
	})
}

// SetDomain sets the "domain" field.
func (u *CheckResultUpsertOne) SetDomain(v string) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateDomain() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateDomain()
	})
}

// SetCategory sets the "category" field.
func (u *CheckResultUpsertOne) SetCategory(v string) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateCategory() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateCategory()
	})
}

// SetStatus sets the "status" field.
func (u *CheckResultUpsertOne) SetStatus(v string) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateStatus() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *CheckResultUpsertOne) SetMessage(v string) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateMessage() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateMessage()
	})
}

// SetSteps sets the "steps" field.
func (u *CheckResultUpsertOne) SetSteps(v string) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetSteps(v)
	})
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateSteps() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateSteps()
	})
}

// SetRanAt sets the "ran_at" field.
func (u *CheckResultUpsertOne) SetRanAt(v time.Time) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetRanAt(v)
	})
}

// UpdateRanAt sets the "ran_at" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateRanAt() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateRanAt()
	})
}

// SetElapsedMs sets the "elapsed_ms" field.
func (u *CheckResultUpsertOne) SetElapsedMs(v int64) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetElapsedMs(v)
	})
}

// AddElapsedMs adds v to the "elapsed_ms" field.
func (u *CheckResultUpsertOne) AddElapsedMs(v int64) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.AddElapsedMs(v)
	})
}

// UpdateElapsedMs sets the "elapsed_ms" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateElapsedMs() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateElapsedMs()
	})
}

// SetFirstFailedAt sets the "first_failed_at" field.
func (u *CheckResultUpsertOne) SetFirstFailedAt(v time.Time) *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetFirstFailedAt(v)
	})
}

// UpdateFirstFailedAt sets the "first_failed_at" field to the value that was provided on create.
func (u *CheckResultUpsertOne) UpdateFirstFailedAt() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateFirstFailedAt()
	})
}

// ClearFirstFailedAt clears the value of the "first_failed_at" field.
func (u *CheckResultUpsertOne) ClearFirstFailedAt() *CheckResultUpsertOne {
	return u.Update(func(s *CheckResultUpsert) {
		s.ClearFirstFailedAt()
	})
}

// Exec executes the query.
func (u *CheckResultUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckResultCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckResultUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckResultUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckResultUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckResultCreateBulk is the builder for creating many CheckResult entities in bulk.
type CheckResultCreateBulk struct {
	config
	err      error
	builders []*CheckResultCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckResult entities in the database.
func (crcb *CheckResultCreateBulk) Save(ctx context.Context) ([]*CheckResult, error) {
	if crcb.err != nil {
		return nil, crcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(crcb.builders))
	nodes := make([]*CheckResult, len(crcb.builders))
	mutators := make([]Mutator, len(crcb.builders))
	for i := range crcb.builders {
		func(i int, root context.Context) {
			builder := crcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, crcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = crcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, crcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, crcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (crcb *CheckResultCreateBulk) SaveX(ctx context.Context) []*CheckResult {
	v, err := crcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crcb *CheckResultCreateBulk) Exec(ctx context.Context) error {
	_, err := crcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crcb *CheckResultCreateBulk) ExecX(ctx context.Context) {
	if err := crcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckResult.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckResultUpsert) {
//			SetCheck(v+v).
//		}).
//		Exec(ctx)
func (crcb *CheckResultCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckResultUpsertBulk {
	crcb.conflict = opts
	return &CheckResultUpsertBulk{
		create: crcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckResult.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (crcb *CheckResultCreateBulk) OnConflictColumns(columns ...string) *CheckResultUpsertBulk {
	crcb.conflict = append(crcb.conflict, sql.ConflictColumns(columns...))
	return &CheckResultUpsertBulk{
		create: crcb,
	}
}

// CheckResultUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckResult nodes.
type CheckResultUpsertBulk struct {
	create *CheckResultCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckResult.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckResultUpsertBulk) UpdateNewValues() *CheckResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckResult.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckResultUpsertBulk) Ignore() *CheckResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckResultUpsertBulk) DoNothing() *CheckResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckResultCreateBulk.OnConflict
// documentation for more info.
func (u *CheckResultUpsertBulk) Update(set func(*CheckResultUpsert)) *CheckResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckResultUpsert{UpdateSet: update})
	}))
	return u
}

// SetCheck sets the "check" field.
func (u *CheckResultUpsertBulk) SetCheck(v string) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetCheck(v)
	})
}

// UpdateCheck sets the "check" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateCheck() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateCheck()
	})
}

// SetDomain sets the "domain" field.
func (u *CheckResultUpsertBulk) SetDomain(v string) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateDomain() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateDomain()
	})
}

// SetCategory sets the "category" field.
func (u *CheckResultUpsertBulk) SetCategory(v string) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateCategory() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateCategory()
	})
}

// SetStatus sets the "status" field.
func (u *CheckResultUpsertBulk) SetStatus(v string) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateStatus() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *CheckResultUpsertBulk) SetMessage(v string) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateMessage() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateMessage()
	})
}

// SetSteps sets the "steps" field.
func (u *CheckResultUpsertBulk) SetSteps(v string) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetSteps(v)
	})
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateSteps() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateSteps()
	})
}

// SetRanAt sets the "ran_at" field.
func (u *CheckResultUpsertBulk) SetRanAt(v time.Time) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetRanAt(v)
	})
}

// UpdateRanAt sets the "ran_at" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateRanAt() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateRanAt()
	})
}

// SetElapsedMs sets the "elapsed_ms" field.
func (u *CheckResultUpsertBulk) SetElapsedMs(v int64) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetElapsedMs(v)
	})
}

// AddElapsedMs adds v to the "elapsed_ms" field.
func (u *CheckResultUpsertBulk) AddElapsedMs(v int64) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.AddElapsedMs(v)
	})
}

// UpdateElapsedMs sets the "elapsed_ms" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateElapsedMs() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateElapsedMs()
	})
}

// SetFirstFailedAt sets the "first_failed_at" field.
func (u *CheckResultUpsertBulk) SetFirstFailedAt(v time.Time) *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.SetFirstFailedAt(v)
	})
}

// UpdateFirstFailedAt sets the "first_failed_at" field to the value that was provided on create.
func (u *CheckResultUpsertBulk) UpdateFirstFailedAt() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.UpdateFirstFailedAt()
	})
}

// ClearFirstFailedAt clears the value of the "first_failed_at" field.
func (u *CheckResultUpsertBulk) ClearFirstFailedAt() *CheckResultUpsertBulk {
	return u.Update(func(s *CheckResultUpsert) {
		s.ClearFirstFailedAt()
	})
}

// Exec executes the query.
func (u *CheckResultUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckResultCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckResultCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckResultUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
