// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/dnsrecord"
	"naust/daemon/internal/store/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DNSRecordCreate is the builder for creating a DNSRecord entity.
type DNSRecordCreate struct {
	config
	mutation *DNSRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQname sets the "qname" field.
func (drc *DNSRecordCreate) SetQname(s string) *DNSRecordCreate {
	drc.mutation.SetQname(s)
	return drc
}

// SetRtype sets the "rtype" field.
func (drc *DNSRecordCreate) SetRtype(d dnsrecord.Rtype) *DNSRecordCreate {
	drc.mutation.SetRtype(d)
	return drc
}

// SetValue sets the "value" field.
func (drc *DNSRecordCreate) SetValue(s string) *DNSRecordCreate {
	drc.mutation.SetValue(s)
	return drc
}

// SetCreatedAt sets the "created_at" field.
func (drc *DNSRecordCreate) SetCreatedAt(t time.Time) *DNSRecordCreate {
	drc.mutation.SetCreatedAt(t)
	return drc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (drc *DNSRecordCreate) SetNillableCreatedAt(t *time.Time) *DNSRecordCreate {
	if t != nil {
		drc.SetCreatedAt(*t)
	}
	return drc
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (drc *DNSRecordCreate) SetTenantID(id int) *DNSRecordCreate {
	drc.mutation.SetTenantID(id)
	return drc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (drc *DNSRecordCreate) SetTenant(t *Tenant) *DNSRecordCreate {
	return drc.SetTenantID(t.ID)
}

// Mutation returns the DNSRecordMutation object of the builder.
func (drc *DNSRecordCreate) Mutation() *DNSRecordMutation {
	return drc.mutation
}

// Save creates the DNSRecord in the database.
func (drc *DNSRecordCreate) Save(ctx context.Context) (*DNSRecord, error) {
	drc.defaults()
	return withHooks(ctx, drc.sqlSave, drc.mutation, drc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (drc *DNSRecordCreate) SaveX(ctx context.Context) *DNSRecord {
	v, err := drc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drc *DNSRecordCreate) Exec(ctx context.Context) error {
	_, err := drc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drc *DNSRecordCreate) ExecX(ctx context.Context) {
	if err := drc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (drc *DNSRecordCreate) defaults() {
	if _, ok := drc.mutation.CreatedAt(); !ok {
		v := dnsrecord.DefaultCreatedAt()
		drc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (drc *DNSRecordCreate) check() error {
	if _, ok := drc.mutation.Qname(); !ok {
		return &ValidationError{Name: "qname", err: errors.New(`ent: missing required field "DNSRecord.qname"`)}
	}
	if v, ok := drc.mutation.Qname(); ok {
		if err := dnsrecord.QnameValidator(v); err != nil {
			return &ValidationError{Name: "qname", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.qname": %w`, err)}
		}
	}
	if _, ok := drc.mutation.Rtype(); !ok {
		return &ValidationError{Name: "rtype", err: errors.New(`ent: missing required field "DNSRecord.rtype"`)}
	}
	if v, ok := drc.mutation.Rtype(); ok {
		if err := dnsrecord.RtypeValidator(v); err != nil {
			return &ValidationError{Name: "rtype", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.rtype": %w`, err)}
		}
	}
	if _, ok := drc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "DNSRecord.value"`)}
	}
	if v, ok := drc.mutation.Value(); ok {
		if err := dnsrecord.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.value": %w`, err)}
		}
	}
	if _, ok := drc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DNSRecord.created_at"`)}
	}
	if _, ok := drc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "DNSRecord.tenant"`)}
	}
	return nil
}

func (drc *DNSRecordCreate) sqlSave(ctx context.Context) (*DNSRecord, error) {
	if err := drc.check(); err != nil {
		return nil, err
	}
	_node, _spec := drc.createSpec()
	if err := sqlgraph.CreateNode(ctx, drc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	drc.mutation.id = &_node.ID
	drc.mutation.done = true
	return _node, nil
}

func (drc *DNSRecordCreate) createSpec() (*DNSRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &DNSRecord{config: drc.config}
		_spec = sqlgraph.NewCreateSpec(dnsrecord.Table, sqlgraph.NewFieldSpec(dnsrecord.FieldID, field.TypeInt))
	)
	_spec.OnConflict = drc.conflict
	if value, ok := drc.mutation.Qname(); ok {
		_spec.SetField(dnsrecord.FieldQname, field.TypeString, value)
		_node.Qname = value
	}
	if value, ok := drc.mutation.Rtype(); ok {
		_spec.SetField(dnsrecord.FieldRtype, field.TypeEnum, value)
		_node.Rtype = value
	}
	if value, ok := drc.mutation.Value(); ok {
		_spec.SetField(dnsrecord.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := drc.mutation.CreatedAt(); ok {
		_spec.SetField(dnsrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := drc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnsrecord.TenantTable,
			Columns: []string{dnsrecord.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_dns_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DNSRecord.Create().
//		SetQname(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DNSRecordUpsert) {
//			SetQname(v+v).
//		}).
//		Exec(ctx)
func (drc *DNSRecordCreate) OnConflict(opts ...sql.ConflictOption) *DNSRecordUpsertOne {
	drc.conflict = opts
	return &DNSRecordUpsertOne{
		create: drc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DNSRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (drc *DNSRecordCreate) OnConflictColumns(columns ...string) *DNSRecordUpsertOne {
	drc.conflict = append(drc.conflict, sql.ConflictColumns(columns...))
	return &DNSRecordUpsertOne{
		create: drc,
	}
}

type (
	// DNSRecordUpsertOne is the builder for "upsert"-ing
	//  one DNSRecord node.
	DNSRecordUpsertOne struct {
		create *DNSRecordCreate
	}

	// DNSRecordUpsert is the "OnConflict" setter.
	DNSRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetQname sets the "qname" field.
func (u *DNSRecordUpsert) SetQname(v string) *DNSRecordUpsert {
	u.Set(dnsrecord.FieldQname, v)
	return u
}

// UpdateQname sets the "qname" field to the value that was provided on create.
func (u *DNSRecordUpsert) UpdateQname() *DNSRecordUpsert {
	u.SetExcluded(dnsrecord.FieldQname)
	return u
}

// SetRtype sets the "rtype" field.
func (u *DNSRecordUpsert) SetRtype(v dnsrecord.Rtype) *DNSRecordUpsert {
	u.Set(dnsrecord.FieldRtype, v)
	return u
}

// UpdateRtype sets the "rtype" field to the value that was provided on create.
func (u *DNSRecordUpsert) UpdateRtype() *DNSRecordUpsert {
	u.SetExcluded(dnsrecord.FieldRtype)
	return u
}

// SetValue sets the "value" field.
func (u *DNSRecordUpsert) SetValue(v string) *DNSRecordUpsert {
	u.Set(dnsrecord.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *DNSRecordUpsert) UpdateValue() *DNSRecordUpsert {
	u.SetExcluded(dnsrecord.FieldValue)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DNSRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DNSRecordUpsertOne) UpdateNewValues() *DNSRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dnsrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DNSRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DNSRecordUpsertOne) Ignore() *DNSRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DNSRecordUpsertOne) DoNothing() *DNSRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DNSRecordCreate.OnConflict
// documentation for more info.
func (u *DNSRecordUpsertOne) Update(set func(*DNSRecordUpsert)) *DNSRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DNSRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetQname sets the "qname" field.
func (u *DNSRecordUpsertOne) SetQname(v string) *DNSRecordUpsertOne {
	return u.Update(func(s *DNSRecordUpsert) {
		s.SetQname(v)
	})
}

// UpdateQname sets the "qname" field to the value that was provided on create.
func (u *DNSRecordUpsertOne) UpdateQname() *DNSRecordUpsertOne {
	return u.Update(func(s *DNSRecordUpsert) {
		s.UpdateQname()
	})
}

// SetRtype sets the "rtype" field.
func (u *DNSRecordUpsertOne) SetRtype(v dnsrecord.Rtype) *DNSRecordUpsertOne {
	return u.Update(func(s *DNSRecordUpsert) {
		s.SetRtype(v)
	})
}

// UpdateRtype sets the "rtype" field to the value that was provided on create.
func (u *DNSRecordUpsertOne) UpdateRtype() *DNSRecordUpsertOne {
	return u.Update(func(s *DNSRecordUpsert) {
		s.UpdateRtype()
	})
}

// SetValue sets the "value" field.
func (u *DNSRecordUpsertOne) SetValue(v string) *DNSRecordUpsertOne {
	return u.Update(func(s *DNSRecordUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *DNSRecordUpsertOne) UpdateValue() *DNSRecordUpsertOne {
	return u.Update(func(s *DNSRecordUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *DNSRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DNSRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DNSRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DNSRecordUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DNSRecordUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DNSRecordCreateBulk is the builder for creating many DNSRecord entities in bulk.
type DNSRecordCreateBulk struct {
	config
	err      error
	builders []*DNSRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the DNSRecord entities in the database.
func (drcb *DNSRecordCreateBulk) Save(ctx context.Context) ([]*DNSRecord, error) {
	if drcb.err != nil {
		return nil, drcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(drcb.builders))
	nodes := make([]*DNSRecord, len(drcb.builders))
	mutators := make([]Mutator, len(drcb.builders))
	for i := range drcb.builders {
		func(i int, root context.Context) {
			builder := drcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DNSRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, drcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = drcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, drcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, drcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (drcb *DNSRecordCreateBulk) SaveX(ctx context.Context) []*DNSRecord {
	v, err := drcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drcb *DNSRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := drcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drcb *DNSRecordCreateBulk) ExecX(ctx context.Context) {
	if err := drcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DNSRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DNSRecordUpsert) {
//			SetQname(v+v).
//		}).
//		Exec(ctx)
func (drcb *DNSRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *DNSRecordUpsertBulk {
	drcb.conflict = opts
	return &DNSRecordUpsertBulk{
		create: drcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DNSRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (drcb *DNSRecordCreateBulk) OnConflictColumns(columns ...string) *DNSRecordUpsertBulk {
	drcb.conflict = append(drcb.conflict, sql.ConflictColumns(columns...))
	return &DNSRecordUpsertBulk{
		create: drcb,
	}
}

// DNSRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of DNSRecord nodes.
type DNSRecordUpsertBulk struct {
	create *DNSRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DNSRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DNSRecordUpsertBulk) UpdateNewValues() *DNSRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dnsrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DNSRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DNSRecordUpsertBulk) Ignore() *DNSRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DNSRecordUpsertBulk) DoNothing() *DNSRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DNSRecordCreateBulk.OnConflict
// documentation for more info.
func (u *DNSRecordUpsertBulk) Update(set func(*DNSRecordUpsert)) *DNSRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DNSRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetQname sets the "qname" field.
func (u *DNSRecordUpsertBulk) SetQname(v string) *DNSRecordUpsertBulk {
	return u.Update(func(s *DNSRecordUpsert) {
		s.SetQname(v)
	})
}

// UpdateQname sets the "qname" field to the value that was provided on create.
func (u *DNSRecordUpsertBulk) UpdateQname() *DNSRecordUpsertBulk {
	return u.Update(func(s *DNSRecordUpsert) {
		s.UpdateQname()
	})
}

// SetRtype sets the "rtype" field.
func (u *DNSRecordUpsertBulk) SetRtype(v dnsrecord.Rtype) *DNSRecordUpsertBulk {
	return u.Update(func(s *DNSRecordUpsert) {
		s.SetRtype(v)
	})
}

// UpdateRtype sets the "rtype" field to the value that was provided on create.
func (u *DNSRecordUpsertBulk) UpdateRtype() *DNSRecordUpsertBulk {
	return u.Update(func(s *DNSRecordUpsert) {
		s.UpdateRtype()
	})
}

// SetValue sets the "value" field.
func (u *DNSRecordUpsertBulk) SetValue(v string) *DNSRecordUpsertBulk {
	return u.Update(func(s *DNSRecordUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *DNSRecordUpsertBulk) UpdateValue() *DNSRecordUpsertBulk {
	return u.Update(func(s *DNSRecordUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *DNSRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DNSRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DNSRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DNSRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
