// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/dnsrecord"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/tenant"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DNSRecordUpdate is the builder for updating DNSRecord entities.
type DNSRecordUpdate struct {
	config
	hooks    []Hook
	mutation *DNSRecordMutation
}

// Where appends a list predicates to the DNSRecordUpdate builder.
func (dru *DNSRecordUpdate) Where(ps ...predicate.DNSRecord) *DNSRecordUpdate {
	dru.mutation.Where(ps...)
	return dru
}

// SetQname sets the "qname" field.
func (dru *DNSRecordUpdate) SetQname(s string) *DNSRecordUpdate {
	dru.mutation.SetQname(s)
	return dru
}

// SetNillableQname sets the "qname" field if the given value is not nil.
func (dru *DNSRecordUpdate) SetNillableQname(s *string) *DNSRecordUpdate {
	if s != nil {
		dru.SetQname(*s)
	}
	return dru
}

// SetRtype sets the "rtype" field.
func (dru *DNSRecordUpdate) SetRtype(d dnsrecord.Rtype) *DNSRecordUpdate {
	dru.mutation.SetRtype(d)
	return dru
}

// SetNillableRtype sets the "rtype" field if the given value is not nil.
func (dru *DNSRecordUpdate) SetNillableRtype(d *dnsrecord.Rtype) *DNSRecordUpdate {
	if d != nil {
		dru.SetRtype(*d)
	}
	return dru
}

// SetValue sets the "value" field.
func (dru *DNSRecordUpdate) SetValue(s string) *DNSRecordUpdate {
	dru.mutation.SetValue(s)
	return dru
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (dru *DNSRecordUpdate) SetNillableValue(s *string) *DNSRecordUpdate {
	if s != nil {
		dru.SetValue(*s)
	}
	return dru
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (dru *DNSRecordUpdate) SetTenantID(id int) *DNSRecordUpdate {
	dru.mutation.SetTenantID(id)
	return dru
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (dru *DNSRecordUpdate) SetTenant(t *Tenant) *DNSRecordUpdate {
	return dru.SetTenantID(t.ID)
}

// Mutation returns the DNSRecordMutation object of the builder.
func (dru *DNSRecordUpdate) Mutation() *DNSRecordMutation {
	return dru.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (dru *DNSRecordUpdate) ClearTenant() *DNSRecordUpdate {
	dru.mutation.ClearTenant()
	return dru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dru *DNSRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dru.sqlSave, dru.mutation, dru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dru *DNSRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := dru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dru *DNSRecordUpdate) Exec(ctx context.Context) error {
	_, err := dru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dru *DNSRecordUpdate) ExecX(ctx context.Context) {
	if err := dru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dru *DNSRecordUpdate) check() error {
	if v, ok := dru.mutation.Qname(); ok {
		if err := dnsrecord.QnameValidator(v); err != nil {
			return &ValidationError{Name: "qname", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.qname": %w`, err)}
		}
	}
	if v, ok := dru.mutation.Rtype(); ok {
		if err := dnsrecord.RtypeValidator(v); err != nil {
			return &ValidationError{Name: "rtype", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.rtype": %w`, err)}
		}
	}
	if v, ok := dru.mutation.Value(); ok {
		if err := dnsrecord.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.value": %w`, err)}
		}
	}
	if _, ok := dru.mutation.TenantID(); dru.mutation.TenantCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "DNSRecord.tenant"`)
	}
	return nil
}

func (dru *DNSRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnsrecord.Table, dnsrecord.Columns, sqlgraph.NewFieldSpec(dnsrecord.FieldID, field.TypeInt))
	if ps := dru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dru.mutation.Qname(); ok {
		_spec.SetField(dnsrecord.FieldQname, field.TypeString, value)
	}
	if value, ok := dru.mutation.Rtype(); ok {
		_spec.SetField(dnsrecord.FieldRtype, field.TypeEnum, value)
	}
	if value, ok := dru.mutation.Value(); ok {
		_spec.SetField(dnsrecord.FieldValue, field.TypeString, value)
	}
	if dru.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnsrecord.TenantTable,
			Columns: []string{dnsrecord.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dru.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnsrecord.TenantTable,
			Columns: []string{dnsrecord.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dru.mutation.done = true
	return n, nil
}

// DNSRecordUpdateOne is the builder for updating a single DNSRecord entity.
type DNSRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DNSRecordMutation
}

// SetQname sets the "qname" field.
func (druo *DNSRecordUpdateOne) SetQname(s string) *DNSRecordUpdateOne {
	druo.mutation.SetQname(s)
	return druo
}

// SetNillableQname sets the "qname" field if the given value is not nil.
func (druo *DNSRecordUpdateOne) SetNillableQname(s *string) *DNSRecordUpdateOne {
	if s != nil {
		druo.SetQname(*s)
	}
	return druo
}

// SetRtype sets the "rtype" field.
func (druo *DNSRecordUpdateOne) SetRtype(d dnsrecord.Rtype) *DNSRecordUpdateOne {
	druo.mutation.SetRtype(d)
	return druo
}

// SetNillableRtype sets the "rtype" field if the given value is not nil.
func (druo *DNSRecordUpdateOne) SetNillableRtype(d *dnsrecord.Rtype) *DNSRecordUpdateOne {
	if d != nil {
		druo.SetRtype(*d)
	}
	return druo
}

// SetValue sets the "value" field.
func (druo *DNSRecordUpdateOne) SetValue(s string) *DNSRecordUpdateOne {
	druo.mutation.SetValue(s)
	return druo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (druo *DNSRecordUpdateOne) SetNillableValue(s *string) *DNSRecordUpdateOne {
	if s != nil {
		druo.SetValue(*s)
	}
	return druo
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (druo *DNSRecordUpdateOne) SetTenantID(id int) *DNSRecordUpdateOne {
	druo.mutation.SetTenantID(id)
	return druo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (druo *DNSRecordUpdateOne) SetTenant(t *Tenant) *DNSRecordUpdateOne {
	return druo.SetTenantID(t.ID)
}

// Mutation returns the DNSRecordMutation object of the builder.
func (druo *DNSRecordUpdateOne) Mutation() *DNSRecordMutation {
	return druo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (druo *DNSRecordUpdateOne) ClearTenant() *DNSRecordUpdateOne {
	druo.mutation.ClearTenant()
	return druo
}

// Where appends a list predicates to the DNSRecordUpdate builder.
func (druo *DNSRecordUpdateOne) Where(ps ...predicate.DNSRecord) *DNSRecordUpdateOne {
	druo.mutation.Where(ps...)
	return druo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (druo *DNSRecordUpdateOne) Select(field string, fields ...string) *DNSRecordUpdateOne {
	druo.fields = append([]string{field}, fields...)
	return druo
}

// Save executes the query and returns the updated DNSRecord entity.
func (druo *DNSRecordUpdateOne) Save(ctx context.Context) (*DNSRecord, error) {
	return withHooks(ctx, druo.sqlSave, druo.mutation, druo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (druo *DNSRecordUpdateOne) SaveX(ctx context.Context) *DNSRecord {
	node, err := druo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (druo *DNSRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := druo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (druo *DNSRecordUpdateOne) ExecX(ctx context.Context) {
	if err := druo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (druo *DNSRecordUpdateOne) check() error {
	if v, ok := druo.mutation.Qname(); ok {
		if err := dnsrecord.QnameValidator(v); err != nil {
			return &ValidationError{Name: "qname", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.qname": %w`, err)}
		}
	}
	if v, ok := druo.mutation.Rtype(); ok {
		if err := dnsrecord.RtypeValidator(v); err != nil {
			return &ValidationError{Name: "rtype", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.rtype": %w`, err)}
		}
	}
	if v, ok := druo.mutation.Value(); ok {
		if err := dnsrecord.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DNSRecord.value": %w`, err)}
		}
	}
	if _, ok := druo.mutation.TenantID(); druo.mutation.TenantCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "DNSRecord.tenant"`)
	}
	return nil
}

func (druo *DNSRecordUpdateOne) sqlSave(ctx context.Context) (_node *DNSRecord, err error) {
	if err := druo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnsrecord.Table, dnsrecord.Columns, sqlgraph.NewFieldSpec(dnsrecord.FieldID, field.TypeInt))
	id, ok := druo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DNSRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := druo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnsrecord.FieldID)
		for _, f := range fields {
			if !dnsrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dnsrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := druo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := druo.mutation.Qname(); ok {
		_spec.SetField(dnsrecord.FieldQname, field.TypeString, value)
	}
	if value, ok := druo.mutation.Rtype(); ok {
		_spec.SetField(dnsrecord.FieldRtype, field.TypeEnum, value)
	}
	if value, ok := druo.mutation.Value(); ok {
		_spec.SetField(dnsrecord.FieldValue, field.TypeString, value)
	}
	if druo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnsrecord.TenantTable,
			Columns: []string{dnsrecord.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := druo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnsrecord.TenantTable,
			Columns: []string{dnsrecord.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DNSRecord{config: druo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, druo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	druo.mutation.done = true
	return _node, nil
}
