// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"naust/daemon/internal/store/ent/mailkeyslot"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailKeySlotQuery is the builder for querying MailKeySlot entities.
type MailKeySlotQuery struct {
	config
	ctx        *QueryContext
	order      []mailkeyslot.OrderOption
	inters     []Interceptor
	predicates []predicate.MailKeySlot
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MailKeySlotQuery builder.
func (mksq *MailKeySlotQuery) Where(ps ...predicate.MailKeySlot) *MailKeySlotQuery {
	mksq.predicates = append(mksq.predicates, ps...)
	return mksq
}

// Limit the number of records to be returned by this query.
func (mksq *MailKeySlotQuery) Limit(limit int) *MailKeySlotQuery {
	mksq.ctx.Limit = &limit
	return mksq
}

// Offset to start from.
func (mksq *MailKeySlotQuery) Offset(offset int) *MailKeySlotQuery {
	mksq.ctx.Offset = &offset
	return mksq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mksq *MailKeySlotQuery) Unique(unique bool) *MailKeySlotQuery {
	mksq.ctx.Unique = &unique
	return mksq
}

// Order specifies how the records should be ordered.
func (mksq *MailKeySlotQuery) Order(o ...mailkeyslot.OrderOption) *MailKeySlotQuery {
	mksq.order = append(mksq.order, o...)
	return mksq
}

// QueryUser chains the current query on the "user" edge.
func (mksq *MailKeySlotQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mksq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mksq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mksq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mailkeyslot.Table, mailkeyslot.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mailkeyslot.UserTable, mailkeyslot.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mksq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MailKeySlot entity from the query.
// Returns a *NotFoundError when no MailKeySlot was found.
func (mksq *MailKeySlotQuery) First(ctx context.Context) (*MailKeySlot, error) {
	nodes, err := mksq.Limit(1).All(setContextOp(ctx, mksq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mailkeyslot.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mksq *MailKeySlotQuery) FirstX(ctx context.Context) *MailKeySlot {
	node, err := mksq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MailKeySlot ID from the query.
// Returns a *NotFoundError when no MailKeySlot ID was found.
func (mksq *MailKeySlotQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mksq.Limit(1).IDs(setContextOp(ctx, mksq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mailkeyslot.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mksq *MailKeySlotQuery) FirstIDX(ctx context.Context) int {
	id, err := mksq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MailKeySlot entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MailKeySlot entity is found.
// Returns a *NotFoundError when no MailKeySlot entities are found.
func (mksq *MailKeySlotQuery) Only(ctx context.Context) (*MailKeySlot, error) {
	nodes, err := mksq.Limit(2).All(setContextOp(ctx, mksq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mailkeyslot.Label}
	default:
		return nil, &NotSingularError{mailkeyslot.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mksq *MailKeySlotQuery) OnlyX(ctx context.Context) *MailKeySlot {
	node, err := mksq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MailKeySlot ID in the query.
// Returns a *NotSingularError when more than one MailKeySlot ID is found.
// Returns a *NotFoundError when no entities are found.
func (mksq *MailKeySlotQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mksq.Limit(2).IDs(setContextOp(ctx, mksq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mailkeyslot.Label}
	default:
		err = &NotSingularError{mailkeyslot.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mksq *MailKeySlotQuery) OnlyIDX(ctx context.Context) int {
	id, err := mksq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MailKeySlots.
func (mksq *MailKeySlotQuery) All(ctx context.Context) ([]*MailKeySlot, error) {
	ctx = setContextOp(ctx, mksq.ctx, "All")
	if err := mksq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MailKeySlot, *MailKeySlotQuery]()
	return withInterceptors[[]*MailKeySlot](ctx, mksq, qr, mksq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mksq *MailKeySlotQuery) AllX(ctx context.Context) []*MailKeySlot {
	nodes, err := mksq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MailKeySlot IDs.
func (mksq *MailKeySlotQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mksq.ctx.Unique == nil && mksq.path != nil {
		mksq.Unique(true)
	}
	ctx = setContextOp(ctx, mksq.ctx, "IDs")
	if err = mksq.Select(mailkeyslot.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mksq *MailKeySlotQuery) IDsX(ctx context.Context) []int {
	ids, err := mksq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mksq *MailKeySlotQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mksq.ctx, "Count")
	if err := mksq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mksq, querierCount[*MailKeySlotQuery](), mksq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mksq *MailKeySlotQuery) CountX(ctx context.Context) int {
	count, err := mksq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mksq *MailKeySlotQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mksq.ctx, "Exist")
	switch _, err := mksq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mksq *MailKeySlotQuery) ExistX(ctx context.Context) bool {
	exist, err := mksq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MailKeySlotQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mksq *MailKeySlotQuery) Clone() *MailKeySlotQuery {
	if mksq == nil {
		return nil
	}
	return &MailKeySlotQuery{
		config:     mksq.config,
		ctx:        mksq.ctx.Clone(),
		order:      append([]mailkeyslot.OrderOption{}, mksq.order...),
		inters:     append([]Interceptor{}, mksq.inters...),
		predicates: append([]predicate.MailKeySlot{}, mksq.predicates...),
		withUser:   mksq.withUser.Clone(),
		// clone intermediate query.
		sql:  mksq.sql.Clone(),
		path: mksq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mksq *MailKeySlotQuery) WithUser(opts ...func(*UserQuery)) *MailKeySlotQuery {
	query := (&UserClient{config: mksq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mksq.withUser = query
	return mksq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SlotType mailkeyslot.SlotType `json:"slot_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MailKeySlot.Query().
//		GroupBy(mailkeyslot.FieldSlotType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mksq *MailKeySlotQuery) GroupBy(field string, fields ...string) *MailKeySlotGroupBy {
	mksq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MailKeySlotGroupBy{build: mksq}
	grbuild.flds = &mksq.ctx.Fields
	grbuild.label = mailkeyslot.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SlotType mailkeyslot.SlotType `json:"slot_type,omitempty"`
//	}
//
//	client.MailKeySlot.Query().
//		Select(mailkeyslot.FieldSlotType).
//		Scan(ctx, &v)
func (mksq *MailKeySlotQuery) Select(fields ...string) *MailKeySlotSelect {
	mksq.ctx.Fields = append(mksq.ctx.Fields, fields...)
	sbuild := &MailKeySlotSelect{MailKeySlotQuery: mksq}
	sbuild.label = mailkeyslot.Label
	sbuild.flds, sbuild.scan = &mksq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MailKeySlotSelect configured with the given aggregations.
func (mksq *MailKeySlotQuery) Aggregate(fns ...AggregateFunc) *MailKeySlotSelect {
	return mksq.Select().Aggregate(fns...)
}

func (mksq *MailKeySlotQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mksq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mksq); err != nil {
				return err
			}
		}
	}
	for _, f := range mksq.ctx.Fields {
		if !mailkeyslot.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mksq.path != nil {
		prev, err := mksq.path(ctx)
		if err != nil {
			return err
		}
		mksq.sql = prev
	}
	return nil
}

func (mksq *MailKeySlotQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MailKeySlot, error) {
	var (
		nodes       = []*MailKeySlot{}
		withFKs     = mksq.withFKs
		_spec       = mksq.querySpec()
		loadedTypes = [1]bool{
			mksq.withUser != nil,
		}
	)
	if mksq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, mailkeyslot.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MailKeySlot).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MailKeySlot{config: mksq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mksq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mksq.withUser; query != nil {
		if err := mksq.loadUser(ctx, query, nodes, nil,
			func(n *MailKeySlot, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mksq *MailKeySlotQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MailKeySlot, init func(*MailKeySlot), assign func(*MailKeySlot, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MailKeySlot)
	for i := range nodes {
		if nodes[i].user_mail_key_slots == nil {
			continue
		}
		fk := *nodes[i].user_mail_key_slots
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_mail_key_slots" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mksq *MailKeySlotQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mksq.querySpec()
	_spec.Node.Columns = mksq.ctx.Fields
	if len(mksq.ctx.Fields) > 0 {
		_spec.Unique = mksq.ctx.Unique != nil && *mksq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mksq.driver, _spec)
}

func (mksq *MailKeySlotQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mailkeyslot.Table, mailkeyslot.Columns, sqlgraph.NewFieldSpec(mailkeyslot.FieldID, field.TypeInt))
	_spec.From = mksq.sql
	if unique := mksq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mksq.path != nil {
		_spec.Unique = true
	}
	if fields := mksq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mailkeyslot.FieldID)
		for i := range fields {
			if fields[i] != mailkeyslot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mksq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mksq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mksq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mksq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mksq *MailKeySlotQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mksq.driver.Dialect())
	t1 := builder.Table(mailkeyslot.Table)
	columns := mksq.ctx.Fields
	if len(columns) == 0 {
		columns = mailkeyslot.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mksq.sql != nil {
		selector = mksq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mksq.ctx.Unique != nil && *mksq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mksq.predicates {
		p(selector)
	}
	for _, p := range mksq.order {
		p(selector)
	}
	if offset := mksq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mksq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MailKeySlotGroupBy is the group-by builder for MailKeySlot entities.
type MailKeySlotGroupBy struct {
	selector
	build *MailKeySlotQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mksgb *MailKeySlotGroupBy) Aggregate(fns ...AggregateFunc) *MailKeySlotGroupBy {
	mksgb.fns = append(mksgb.fns, fns...)
	return mksgb
}

// Scan applies the selector query and scans the result into the given value.
func (mksgb *MailKeySlotGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mksgb.build.ctx, "GroupBy")
	if err := mksgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MailKeySlotQuery, *MailKeySlotGroupBy](ctx, mksgb.build, mksgb, mksgb.build.inters, v)
}

func (mksgb *MailKeySlotGroupBy) sqlScan(ctx context.Context, root *MailKeySlotQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mksgb.fns))
	for _, fn := range mksgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mksgb.flds)+len(mksgb.fns))
		for _, f := range *mksgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mksgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mksgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MailKeySlotSelect is the builder for selecting fields of MailKeySlot entities.
type MailKeySlotSelect struct {
	*MailKeySlotQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mkss *MailKeySlotSelect) Aggregate(fns ...AggregateFunc) *MailKeySlotSelect {
	mkss.fns = append(mkss.fns, fns...)
	return mkss
}

// Scan applies the selector query and scans the result into the given value.
func (mkss *MailKeySlotSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mkss.ctx, "Select")
	if err := mkss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MailKeySlotQuery, *MailKeySlotSelect](ctx, mkss.MailKeySlotQuery, mkss, mkss.inters, v)
}

func (mkss *MailKeySlotSelect) sqlScan(ctx context.Context, root *MailKeySlotQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mkss.fns))
	for _, fn := range mkss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mkss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mkss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
