// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/metricsample"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MetricSampleCreate is the builder for creating a MetricSample entity.
type MetricSampleCreate struct {
	config
	mutation *MetricSampleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMetric sets the "metric" field.
func (msc *MetricSampleCreate) SetMetric(s string) *MetricSampleCreate {
	msc.mutation.SetMetric(s)
	return msc
}

// SetSampledAt sets the "sampled_at" field.
func (msc *MetricSampleCreate) SetSampledAt(t time.Time) *MetricSampleCreate {
	msc.mutation.SetSampledAt(t)
	return msc
}

// SetValue sets the "value" field.
func (msc *MetricSampleCreate) SetValue(f float64) *MetricSampleCreate {
	msc.mutation.SetValue(f)
	return msc
}

// Mutation returns the MetricSampleMutation object of the builder.
func (msc *MetricSampleCreate) Mutation() *MetricSampleMutation {
	return msc.mutation
}

// Save creates the MetricSample in the database.
func (msc *MetricSampleCreate) Save(ctx context.Context) (*MetricSample, error) {
	return withHooks(ctx, msc.sqlSave, msc.mutation, msc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (msc *MetricSampleCreate) SaveX(ctx context.Context) *MetricSample {
	v, err := msc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (msc *MetricSampleCreate) Exec(ctx context.Context) error {
	_, err := msc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (msc *MetricSampleCreate) ExecX(ctx context.Context) {
	if err := msc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (msc *MetricSampleCreate) check() error {
	if _, ok := msc.mutation.Metric(); !ok {
		return &ValidationError{Name: "metric", err: errors.New(`ent: missing required field "MetricSample.metric"`)}
	}
	if v, ok := msc.mutation.Metric(); ok {
		if err := metricsample.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "MetricSample.metric": %w`, err)}
		}
	}
	if _, ok := msc.mutation.SampledAt(); !ok {
		return &ValidationError{Name: "sampled_at", err: errors.New(`ent: missing required field "MetricSample.sampled_at"`)}
	}
	if _, ok := msc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "MetricSample.value"`)}
	}
	return nil
}

func (msc *MetricSampleCreate) sqlSave(ctx context.Context) (*MetricSample, error) {
	if err := msc.check(); err != nil {
		return nil, err
	}
	_node, _spec := msc.createSpec()
	if err := sqlgraph.CreateNode(ctx, msc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	msc.mutation.id = &_node.ID
	msc.mutation.done = true
	return _node, nil
}

func (msc *MetricSampleCreate) createSpec() (*MetricSample, *sqlgraph.CreateSpec) {
	var (
		_node = &MetricSample{config: msc.config}
		_spec = sqlgraph.NewCreateSpec(metricsample.Table, sqlgraph.NewFieldSpec(metricsample.FieldID, field.TypeInt))
	)
	_spec.OnConflict = msc.conflict
	if value, ok := msc.mutation.Metric(); ok {
		_spec.SetField(metricsample.FieldMetric, field.TypeString, value)
		_node.Metric = value
	}
	if value, ok := msc.mutation.SampledAt(); ok {
		_spec.SetField(metricsample.FieldSampledAt, field.TypeTime, value)
		_node.SampledAt = value
	}
	if value, ok := msc.mutation.Value(); ok {
		_spec.SetField(metricsample.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MetricSample.Create().
//		SetMetric(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MetricSampleUpsert) {
//			SetMetric(v+v).
//		}).
//		Exec(ctx)
func (msc *MetricSampleCreate) OnConflict(opts ...sql.ConflictOption) *MetricSampleUpsertOne {
	msc.conflict = opts
	return &MetricSampleUpsertOne{
		create: msc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MetricSample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (msc *MetricSampleCreate) OnConflictColumns(columns ...string) *MetricSampleUpsertOne {
	msc.conflict = append(msc.conflict, sql.ConflictColumns(columns...))
	return &MetricSampleUpsertOne{
		create: msc,
	}
}

type (
	// MetricSampleUpsertOne is the builder for "upsert"-ing
	//  one MetricSample node.
	MetricSampleUpsertOne struct {
		create *MetricSampleCreate
	}

	// MetricSampleUpsert is the "OnConflict" setter.
	MetricSampleUpsert struct {
		*sql.UpdateSet
	}
)

// SetMetric sets the "metric" field.
func (u *MetricSampleUpsert) SetMetric(v string) *MetricSampleUpsert {
	u.Set(metricsample.FieldMetric, v)
	return u
}

// UpdateMetric sets the "metric" field to the value that was provided on create.
func (u *MetricSampleUpsert) UpdateMetric() *MetricSampleUpsert {
	u.SetExcluded(metricsample.FieldMetric)
	return u
}

// SetSampledAt sets the "sampled_at" field.
func (u *MetricSampleUpsert) SetSampledAt(v time.Time) *MetricSampleUpsert {
	u.Set(metricsample.FieldSampledAt, v)
	return u
}

// UpdateSampledAt sets the "sampled_at" field to the value that was provided on create.
func (u *MetricSampleUpsert) UpdateSampledAt() *MetricSampleUpsert {
	u.SetExcluded(metricsample.FieldSampledAt)
	return u
}

// SetValue sets the "value" field.
func (u *MetricSampleUpsert) SetValue(v float64) *MetricSampleUpsert {
	u.Set(metricsample.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *MetricSampleUpsert) UpdateValue() *MetricSampleUpsert {
	u.SetExcluded(metricsample.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *MetricSampleUpsert) AddValue(v float64) *MetricSampleUpsert {
	u.Add(metricsample.FieldValue, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MetricSample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MetricSampleUpsertOne) UpdateNewValues() *MetricSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MetricSample.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MetricSampleUpsertOne) Ignore() *MetricSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MetricSampleUpsertOne) DoNothing() *MetricSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MetricSampleCreate.OnConflict
// documentation for more info.
func (u *MetricSampleUpsertOne) Update(set func(*MetricSampleUpsert)) *MetricSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MetricSampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetMetric sets the "metric" field.
func (u *MetricSampleUpsertOne) SetMetric(v string) *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.SetMetric(v)
	})
}

// UpdateMetric sets the "metric" field to the value that was provided on create.
func (u *MetricSampleUpsertOne) UpdateMetric() *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.UpdateMetric()
	})
}

// SetSampledAt sets the "sampled_at" field.
func (u *MetricSampleUpsertOne) SetSampledAt(v time.Time) *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.SetSampledAt(v)
	})
}

// UpdateSampledAt sets the "sampled_at" field to the value that was provided on create.
func (u *MetricSampleUpsertOne) UpdateSampledAt() *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.UpdateSampledAt()
	})
}

// SetValue sets the "value" field.
func (u *MetricSampleUpsertOne) SetValue(v float64) *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *MetricSampleUpsertOne) AddValue(v float64) *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *MetricSampleUpsertOne) UpdateValue() *MetricSampleUpsertOne {
	return u.Update(func(s *MetricSampleUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *MetricSampleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MetricSampleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MetricSampleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MetricSampleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MetricSampleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MetricSampleCreateBulk is the builder for creating many MetricSample entities in bulk.
type MetricSampleCreateBulk struct {
	config
	err      error
	builders []*MetricSampleCreate
	conflict []sql.ConflictOption
}

// Save creates the MetricSample entities in the database.
func (mscb *MetricSampleCreateBulk) Save(ctx context.Context) ([]*MetricSample, error) {
	if mscb.err != nil {
		return nil, mscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mscb.builders))
	nodes := make([]*MetricSample, len(mscb.builders))
	mutators := make([]Mutator, len(mscb.builders))
	for i := range mscb.builders {
		func(i int, root context.Context) {
			builder := mscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MetricSampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mscb *MetricSampleCreateBulk) SaveX(ctx context.Context) []*MetricSample {
	v, err := mscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mscb *MetricSampleCreateBulk) Exec(ctx context.Context) error {
	_, err := mscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mscb *MetricSampleCreateBulk) ExecX(ctx context.Context) {
	if err := mscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MetricSample.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MetricSampleUpsert) {
//			SetMetric(v+v).
//		}).
//		Exec(ctx)
func (mscb *MetricSampleCreateBulk) OnConflict(opts ...sql.ConflictOption) *MetricSampleUpsertBulk {
	mscb.conflict = opts
	return &MetricSampleUpsertBulk{
		create: mscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MetricSample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mscb *MetricSampleCreateBulk) OnConflictColumns(columns ...string) *MetricSampleUpsertBulk {
	mscb.conflict = append(mscb.conflict, sql.ConflictColumns(columns...))
	return &MetricSampleUpsertBulk{
		create: mscb,
	}
}

// MetricSampleUpsertBulk is the builder for "upsert"-ing
// a bulk of MetricSample nodes.
type MetricSampleUpsertBulk struct {
	create *MetricSampleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MetricSample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MetricSampleUpsertBulk) UpdateNewValues() *MetricSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MetricSample.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MetricSampleUpsertBulk) Ignore() *MetricSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MetricSampleUpsertBulk) DoNothing() *MetricSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MetricSampleCreateBulk.OnConflict
// documentation for more info.
func (u *MetricSampleUpsertBulk) Update(set func(*MetricSampleUpsert)) *MetricSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MetricSampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetMetric sets the "metric" field.
func (u *MetricSampleUpsertBulk) SetMetric(v string) *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.SetMetric(v)
	})
}

// UpdateMetric sets the "metric" field to the value that was provided on create.
func (u *MetricSampleUpsertBulk) UpdateMetric() *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.UpdateMetric()
	})
}

// SetSampledAt sets the "sampled_at" field.
func (u *MetricSampleUpsertBulk) SetSampledAt(v time.Time) *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.SetSampledAt(v)
	})
}

// UpdateSampledAt sets the "sampled_at" field to the value that was provided on create.
func (u *MetricSampleUpsertBulk) UpdateSampledAt() *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.UpdateSampledAt()
	})
}

// SetValue sets the "value" field.
func (u *MetricSampleUpsertBulk) SetValue(v float64) *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *MetricSampleUpsertBulk) AddValue(v float64) *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *MetricSampleUpsertBulk) UpdateValue() *MetricSampleUpsertBulk {
	return u.Update(func(s *MetricSampleUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *MetricSampleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MetricSampleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MetricSampleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MetricSampleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
