// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/metricsample"
	"naust/daemon/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MetricSampleUpdate is the builder for updating MetricSample entities.
type MetricSampleUpdate struct {
	config
	hooks    []Hook
	mutation *MetricSampleMutation
}

// Where appends a list predicates to the MetricSampleUpdate builder.
func (msu *MetricSampleUpdate) Where(ps ...predicate.MetricSample) *MetricSampleUpdate {
	msu.mutation.Where(ps...)
	return msu
}

// SetMetric sets the "metric" field.
func (msu *MetricSampleUpdate) SetMetric(s string) *MetricSampleUpdate {
	msu.mutation.SetMetric(s)
	return msu
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (msu *MetricSampleUpdate) SetNillableMetric(s *string) *MetricSampleUpdate {
	if s != nil {
		msu.SetMetric(*s)
	}
	return msu
}

// SetSampledAt sets the "sampled_at" field.
func (msu *MetricSampleUpdate) SetSampledAt(t time.Time) *MetricSampleUpdate {
	msu.mutation.SetSampledAt(t)
	return msu
}

// SetNillableSampledAt sets the "sampled_at" field if the given value is not nil.
func (msu *MetricSampleUpdate) SetNillableSampledAt(t *time.Time) *MetricSampleUpdate {
	if t != nil {
		msu.SetSampledAt(*t)
	}
	return msu
}

// SetValue sets the "value" field.
func (msu *MetricSampleUpdate) SetValue(f float64) *MetricSampleUpdate {
	msu.mutation.ResetValue()
	msu.mutation.SetValue(f)
	return msu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (msu *MetricSampleUpdate) SetNillableValue(f *float64) *MetricSampleUpdate {
	if f != nil {
		msu.SetValue(*f)
	}
	return msu
}

// AddValue adds f to the "value" field.
func (msu *MetricSampleUpdate) AddValue(f float64) *MetricSampleUpdate {
	msu.mutation.AddValue(f)
	return msu
}

// Mutation returns the MetricSampleMutation object of the builder.
func (msu *MetricSampleUpdate) Mutation() *MetricSampleMutation {
	return msu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (msu *MetricSampleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, msu.sqlSave, msu.mutation, msu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (msu *MetricSampleUpdate) SaveX(ctx context.Context) int {
	affected, err := msu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (msu *MetricSampleUpdate) Exec(ctx context.Context) error {
	_, err := msu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (msu *MetricSampleUpdate) ExecX(ctx context.Context) {
	if err := msu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (msu *MetricSampleUpdate) check() error {
	if v, ok := msu.mutation.Metric(); ok {
		if err := metricsample.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "MetricSample.metric": %w`, err)}
		}
	}
	return nil
}

func (msu *MetricSampleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := msu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(metricsample.Table, metricsample.Columns, sqlgraph.NewFieldSpec(metricsample.FieldID, field.TypeInt))
	if ps := msu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := msu.mutation.Metric(); ok {
		_spec.SetField(metricsample.FieldMetric, field.TypeString, value)
	}
	if value, ok := msu.mutation.SampledAt(); ok {
		_spec.SetField(metricsample.FieldSampledAt, field.TypeTime, value)
	}
	if value, ok := msu.mutation.Value(); ok {
		_spec.SetField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := msu.mutation.AddedValue(); ok {
		_spec.AddField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, msu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metricsample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	msu.mutation.done = true
	return n, nil
}

// MetricSampleUpdateOne is the builder for updating a single MetricSample entity.
type MetricSampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetricSampleMutation
}

// SetMetric sets the "metric" field.
func (msuo *MetricSampleUpdateOne) SetMetric(s string) *MetricSampleUpdateOne {
	msuo.mutation.SetMetric(s)
	return msuo
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (msuo *MetricSampleUpdateOne) SetNillableMetric(s *string) *MetricSampleUpdateOne {
	if s != nil {
		msuo.SetMetric(*s)
	}
	return msuo
}

// SetSampledAt sets the "sampled_at" field.
func (msuo *MetricSampleUpdateOne) SetSampledAt(t time.Time) *MetricSampleUpdateOne {
	msuo.mutation.SetSampledAt(t)
	return msuo
}

// SetNillableSampledAt sets the "sampled_at" field if the given value is not nil.
func (msuo *MetricSampleUpdateOne) SetNillableSampledAt(t *time.Time) *MetricSampleUpdateOne {
	if t != nil {
		msuo.SetSampledAt(*t)
	}
	return msuo
}

// SetValue sets the "value" field.
func (msuo *MetricSampleUpdateOne) SetValue(f float64) *MetricSampleUpdateOne {
	msuo.mutation.ResetValue()
	msuo.mutation.SetValue(f)
	return msuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (msuo *MetricSampleUpdateOne) SetNillableValue(f *float64) *MetricSampleUpdateOne {
	if f != nil {
		msuo.SetValue(*f)
	}
	return msuo
}

// AddValue adds f to the "value" field.
func (msuo *MetricSampleUpdateOne) AddValue(f float64) *MetricSampleUpdateOne {
	msuo.mutation.AddValue(f)
	return msuo
}

// Mutation returns the MetricSampleMutation object of the builder.
func (msuo *MetricSampleUpdateOne) Mutation() *MetricSampleMutation {
	return msuo.mutation
}

// Where appends a list predicates to the MetricSampleUpdate builder.
func (msuo *MetricSampleUpdateOne) Where(ps ...predicate.MetricSample) *MetricSampleUpdateOne {
	msuo.mutation.Where(ps...)
	return msuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (msuo *MetricSampleUpdateOne) Select(field string, fields ...string) *MetricSampleUpdateOne {
	msuo.fields = append([]string{field}, fields...)
	return msuo
}

// Save executes the query and returns the updated MetricSample entity.
func (msuo *MetricSampleUpdateOne) Save(ctx context.Context) (*MetricSample, error) {
	return withHooks(ctx, msuo.sqlSave, msuo.mutation, msuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (msuo *MetricSampleUpdateOne) SaveX(ctx context.Context) *MetricSample {
	node, err := msuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (msuo *MetricSampleUpdateOne) Exec(ctx context.Context) error {
	_, err := msuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (msuo *MetricSampleUpdateOne) ExecX(ctx context.Context) {
	if err := msuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (msuo *MetricSampleUpdateOne) check() error {
	if v, ok := msuo.mutation.Metric(); ok {
		if err := metricsample.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "MetricSample.metric": %w`, err)}
		}
	}
	return nil
}

func (msuo *MetricSampleUpdateOne) sqlSave(ctx context.Context) (_node *MetricSample, err error) {
	if err := msuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(metricsample.Table, metricsample.Columns, sqlgraph.NewFieldSpec(metricsample.FieldID, field.TypeInt))
	id, ok := msuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MetricSample.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := msuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, metricsample.FieldID)
		for _, f := range fields {
			if !metricsample.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != metricsample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := msuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := msuo.mutation.Metric(); ok {
		_spec.SetField(metricsample.FieldMetric, field.TypeString, value)
	}
	if value, ok := msuo.mutation.SampledAt(); ok {
		_spec.SetField(metricsample.FieldSampledAt, field.TypeTime, value)
	}
	if value, ok := msuo.mutation.Value(); ok {
		_spec.SetField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := msuo.mutation.AddedValue(); ok {
		_spec.AddField(metricsample.FieldValue, field.TypeFloat64, value)
	}
	_node = &MetricSample{config: msuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, msuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metricsample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	msuo.mutation.done = true
	return _node, nil
}
