// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"naust/daemon/internal/store/ent/metricsample"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MetricSample is the model entity for the MetricSample schema.
type MetricSample struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Metric holds the value of the "metric" field.
	Metric string `json:"metric,omitempty"`
	// SampledAt holds the value of the "sampled_at" field.
	SampledAt time.Time `json:"sampled_at,omitempty"`
	// Value holds the value of the "value" field.
	Value        float64 `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MetricSample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case metricsample.FieldValue:
			values[i] = new(sql.NullFloat64)
		case metricsample.FieldID:
			values[i] = new(sql.NullInt64)
		case metricsample.FieldMetric:
			values[i] = new(sql.NullString)
		case metricsample.FieldSampledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MetricSample fields.
func (ms *MetricSample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case metricsample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ms.ID = int(value.Int64)
		case metricsample.FieldMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric", values[i])
			} else if value.Valid {
				ms.Metric = value.String
			}
		case metricsample.FieldSampledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sampled_at", values[i])
			} else if value.Valid {
				ms.SampledAt = value.Time
			}
		case metricsample.FieldValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				ms.Value = value.Float64
			}
		default:
			ms.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the MetricSample.
// This includes values selected through modifiers, order, etc.
func (ms *MetricSample) GetValue(name string) (ent.Value, error) {
	return ms.selectValues.Get(name)
}

// Update returns a builder for updating this MetricSample.
// Note that you need to call MetricSample.Unwrap() before calling this method if this MetricSample
// was returned from a transaction, and the transaction was committed or rolled back.
func (ms *MetricSample) Update() *MetricSampleUpdateOne {
	return NewMetricSampleClient(ms.config).UpdateOne(ms)
}

// Unwrap unwraps the MetricSample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ms *MetricSample) Unwrap() *MetricSample {
	_tx, ok := ms.config.driver.(*txDriver)
	if !ok {
		panic("ent: MetricSample is not a transactional entity")
	}
	ms.config.driver = _tx.drv
	return ms
}

// String implements the fmt.Stringer.
func (ms *MetricSample) String() string {
	var builder strings.Builder
	builder.WriteString("MetricSample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ms.ID))
	builder.WriteString("metric=")
	builder.WriteString(ms.Metric)
	builder.WriteString(", ")
	builder.WriteString("sampled_at=")
	builder.WriteString(ms.SampledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", ms.Value))
	builder.WriteByte(')')
	return builder.String()
}

// MetricSamples is a parsable slice of MetricSample.
type MetricSamples []*MetricSample
