// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/totpcredential"
	"naust/daemon/internal/store/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TOTPCredentialUpdate is the builder for updating TOTPCredential entities.
type TOTPCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *TOTPCredentialMutation
}

// Where appends a list predicates to the TOTPCredentialUpdate builder.
func (tcu *TOTPCredentialUpdate) Where(ps ...predicate.TOTPCredential) *TOTPCredentialUpdate {
	tcu.mutation.Where(ps...)
	return tcu
}

// SetSecret sets the "secret" field.
func (tcu *TOTPCredentialUpdate) SetSecret(s string) *TOTPCredentialUpdate {
	tcu.mutation.SetSecret(s)
	return tcu
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (tcu *TOTPCredentialUpdate) SetNillableSecret(s *string) *TOTPCredentialUpdate {
	if s != nil {
		tcu.SetSecret(*s)
	}
	return tcu
}

// SetMruToken sets the "mru_token" field.
func (tcu *TOTPCredentialUpdate) SetMruToken(s string) *TOTPCredentialUpdate {
	tcu.mutation.SetMruToken(s)
	return tcu
}

// SetNillableMruToken sets the "mru_token" field if the given value is not nil.
func (tcu *TOTPCredentialUpdate) SetNillableMruToken(s *string) *TOTPCredentialUpdate {
	if s != nil {
		tcu.SetMruToken(*s)
	}
	return tcu
}

// ClearMruToken clears the value of the "mru_token" field.
func (tcu *TOTPCredentialUpdate) ClearMruToken() *TOTPCredentialUpdate {
	tcu.mutation.ClearMruToken()
	return tcu
}

// SetLabel sets the "label" field.
func (tcu *TOTPCredentialUpdate) SetLabel(s string) *TOTPCredentialUpdate {
	tcu.mutation.SetLabel(s)
	return tcu
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (tcu *TOTPCredentialUpdate) SetNillableLabel(s *string) *TOTPCredentialUpdate {
	if s != nil {
		tcu.SetLabel(*s)
	}
	return tcu
}

// ClearLabel clears the value of the "label" field.
func (tcu *TOTPCredentialUpdate) ClearLabel() *TOTPCredentialUpdate {
	tcu.mutation.ClearLabel()
	return tcu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (tcu *TOTPCredentialUpdate) SetUserID(id int) *TOTPCredentialUpdate {
	tcu.mutation.SetUserID(id)
	return tcu
}

// SetUser sets the "user" edge to the User entity.
func (tcu *TOTPCredentialUpdate) SetUser(u *User) *TOTPCredentialUpdate {
	return tcu.SetUserID(u.ID)
}

// Mutation returns the TOTPCredentialMutation object of the builder.
func (tcu *TOTPCredentialUpdate) Mutation() *TOTPCredentialMutation {
	return tcu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (tcu *TOTPCredentialUpdate) ClearUser() *TOTPCredentialUpdate {
	tcu.mutation.ClearUser()
	return tcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tcu *TOTPCredentialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tcu.sqlSave, tcu.mutation, tcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tcu *TOTPCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := tcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tcu *TOTPCredentialUpdate) Exec(ctx context.Context) error {
	_, err := tcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcu *TOTPCredentialUpdate) ExecX(ctx context.Context) {
	if err := tcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcu *TOTPCredentialUpdate) check() error {
	if v, ok := tcu.mutation.Secret(); ok {
		if err := totpcredential.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "TOTPCredential.secret": %w`, err)}
		}
	}
	if _, ok := tcu.mutation.UserID(); tcu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "TOTPCredential.user"`)
	}
	return nil
}

func (tcu *TOTPCredentialUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(totpcredential.Table, totpcredential.Columns, sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt))
	if ps := tcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tcu.mutation.Secret(); ok {
		_spec.SetField(totpcredential.FieldSecret, field.TypeString, value)
	}
	if value, ok := tcu.mutation.MruToken(); ok {
		_spec.SetField(totpcredential.FieldMruToken, field.TypeString, value)
	}
	if tcu.mutation.MruTokenCleared() {
		_spec.ClearField(totpcredential.FieldMruToken, field.TypeString)
	}
	if value, ok := tcu.mutation.Label(); ok {
		_spec.SetField(totpcredential.FieldLabel, field.TypeString, value)
	}
	if tcu.mutation.LabelCleared() {
		_spec.ClearField(totpcredential.FieldLabel, field.TypeString)
	}
	if tcu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpcredential.UserTable,
			Columns: []string{totpcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tcu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpcredential.UserTable,
			Columns: []string{totpcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{totpcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tcu.mutation.done = true
	return n, nil
}

// TOTPCredentialUpdateOne is the builder for updating a single TOTPCredential entity.
type TOTPCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TOTPCredentialMutation
}

// SetSecret sets the "secret" field.
func (tcuo *TOTPCredentialUpdateOne) SetSecret(s string) *TOTPCredentialUpdateOne {
	tcuo.mutation.SetSecret(s)
	return tcuo
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (tcuo *TOTPCredentialUpdateOne) SetNillableSecret(s *string) *TOTPCredentialUpdateOne {
	if s != nil {
		tcuo.SetSecret(*s)
	}
	return tcuo
}

// SetMruToken sets the "mru_token" field.
func (tcuo *TOTPCredentialUpdateOne) SetMruToken(s string) *TOTPCredentialUpdateOne {
	tcuo.mutation.SetMruToken(s)
	return tcuo
}

// SetNillableMruToken sets the "mru_token" field if the given value is not nil.
func (tcuo *TOTPCredentialUpdateOne) SetNillableMruToken(s *string) *TOTPCredentialUpdateOne {
	if s != nil {
		tcuo.SetMruToken(*s)
	}
	return tcuo
}

// ClearMruToken clears the value of the "mru_token" field.
func (tcuo *TOTPCredentialUpdateOne) ClearMruToken() *TOTPCredentialUpdateOne {
	tcuo.mutation.ClearMruToken()
	return tcuo
}

// SetLabel sets the "label" field.
func (tcuo *TOTPCredentialUpdateOne) SetLabel(s string) *TOTPCredentialUpdateOne {
	tcuo.mutation.SetLabel(s)
	return tcuo
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (tcuo *TOTPCredentialUpdateOne) SetNillableLabel(s *string) *TOTPCredentialUpdateOne {
	if s != nil {
		tcuo.SetLabel(*s)
	}
	return tcuo
}

// ClearLabel clears the value of the "label" field.
func (tcuo *TOTPCredentialUpdateOne) ClearLabel() *TOTPCredentialUpdateOne {
	tcuo.mutation.ClearLabel()
	return tcuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (tcuo *TOTPCredentialUpdateOne) SetUserID(id int) *TOTPCredentialUpdateOne {
	tcuo.mutation.SetUserID(id)
	return tcuo
}

// SetUser sets the "user" edge to the User entity.
func (tcuo *TOTPCredentialUpdateOne) SetUser(u *User) *TOTPCredentialUpdateOne {
	return tcuo.SetUserID(u.ID)
}

// Mutation returns the TOTPCredentialMutation object of the builder.
func (tcuo *TOTPCredentialUpdateOne) Mutation() *TOTPCredentialMutation {
	return tcuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (tcuo *TOTPCredentialUpdateOne) ClearUser() *TOTPCredentialUpdateOne {
	tcuo.mutation.ClearUser()
	return tcuo
}

// Where appends a list predicates to the TOTPCredentialUpdate builder.
func (tcuo *TOTPCredentialUpdateOne) Where(ps ...predicate.TOTPCredential) *TOTPCredentialUpdateOne {
	tcuo.mutation.Where(ps...)
	return tcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tcuo *TOTPCredentialUpdateOne) Select(field string, fields ...string) *TOTPCredentialUpdateOne {
	tcuo.fields = append([]string{field}, fields...)
	return tcuo
}

// Save executes the query and returns the updated TOTPCredential entity.
func (tcuo *TOTPCredentialUpdateOne) Save(ctx context.Context) (*TOTPCredential, error) {
	return withHooks(ctx, tcuo.sqlSave, tcuo.mutation, tcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tcuo *TOTPCredentialUpdateOne) SaveX(ctx context.Context) *TOTPCredential {
	node, err := tcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tcuo *TOTPCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := tcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcuo *TOTPCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := tcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcuo *TOTPCredentialUpdateOne) check() error {
	if v, ok := tcuo.mutation.Secret(); ok {
		if err := totpcredential.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "TOTPCredential.secret": %w`, err)}
		}
	}
	if _, ok := tcuo.mutation.UserID(); tcuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "TOTPCredential.user"`)
	}
	return nil
}

func (tcuo *TOTPCredentialUpdateOne) sqlSave(ctx context.Context) (_node *TOTPCredential, err error) {
	if err := tcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(totpcredential.Table, totpcredential.Columns, sqlgraph.NewFieldSpec(totpcredential.FieldID, field.TypeInt))
	id, ok := tcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TOTPCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, totpcredential.FieldID)
		for _, f := range fields {
			if !totpcredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != totpcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tcuo.mutation.Secret(); ok {
		_spec.SetField(totpcredential.FieldSecret, field.TypeString, value)
	}
	if value, ok := tcuo.mutation.MruToken(); ok {
		_spec.SetField(totpcredential.FieldMruToken, field.TypeString, value)
	}
	if tcuo.mutation.MruTokenCleared() {
		_spec.ClearField(totpcredential.FieldMruToken, field.TypeString)
	}
	if value, ok := tcuo.mutation.Label(); ok {
		_spec.SetField(totpcredential.FieldLabel, field.TypeString, value)
	}
	if tcuo.mutation.LabelCleared() {
		_spec.ClearField(totpcredential.FieldLabel, field.TypeString)
	}
	if tcuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpcredential.UserTable,
			Columns: []string{totpcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tcuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpcredential.UserTable,
			Columns: []string{totpcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TOTPCredential{config: tcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{totpcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tcuo.mutation.done = true
	return _node, nil
}
