// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/user"
	"naust/daemon/internal/store/ent/webauthnchallenge"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebAuthnChallengeUpdate is the builder for updating WebAuthnChallenge entities.
type WebAuthnChallengeUpdate struct {
	config
	hooks    []Hook
	mutation *WebAuthnChallengeMutation
}

// Where appends a list predicates to the WebAuthnChallengeUpdate builder.
func (wacu *WebAuthnChallengeUpdate) Where(ps ...predicate.WebAuthnChallenge) *WebAuthnChallengeUpdate {
	wacu.mutation.Where(ps...)
	return wacu
}

// SetNonceHash sets the "nonce_hash" field.
func (wacu *WebAuthnChallengeUpdate) SetNonceHash(s string) *WebAuthnChallengeUpdate {
	wacu.mutation.SetNonceHash(s)
	return wacu
}

// SetNillableNonceHash sets the "nonce_hash" field if the given value is not nil.
func (wacu *WebAuthnChallengeUpdate) SetNillableNonceHash(s *string) *WebAuthnChallengeUpdate {
	if s != nil {
		wacu.SetNonceHash(*s)
	}
	return wacu
}

// SetSessionData sets the "session_data" field.
func (wacu *WebAuthnChallengeUpdate) SetSessionData(s string) *WebAuthnChallengeUpdate {
	wacu.mutation.SetSessionData(s)
	return wacu
}

// SetNillableSessionData sets the "session_data" field if the given value is not nil.
func (wacu *WebAuthnChallengeUpdate) SetNillableSessionData(s *string) *WebAuthnChallengeUpdate {
	if s != nil {
		wacu.SetSessionData(*s)
	}
	return wacu
}

// SetKind sets the "kind" field.
func (wacu *WebAuthnChallengeUpdate) SetKind(w webauthnchallenge.Kind) *WebAuthnChallengeUpdate {
	wacu.mutation.SetKind(w)
	return wacu
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (wacu *WebAuthnChallengeUpdate) SetNillableKind(w *webauthnchallenge.Kind) *WebAuthnChallengeUpdate {
	if w != nil {
		wacu.SetKind(*w)
	}
	return wacu
}

// SetExpiresAt sets the "expires_at" field.
func (wacu *WebAuthnChallengeUpdate) SetExpiresAt(t time.Time) *WebAuthnChallengeUpdate {
	wacu.mutation.SetExpiresAt(t)
	return wacu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (wacu *WebAuthnChallengeUpdate) SetNillableExpiresAt(t *time.Time) *WebAuthnChallengeUpdate {
	if t != nil {
		wacu.SetExpiresAt(*t)
	}
	return wacu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (wacu *WebAuthnChallengeUpdate) SetUserID(id int) *WebAuthnChallengeUpdate {
	wacu.mutation.SetUserID(id)
	return wacu
}

// SetUser sets the "user" edge to the User entity.
func (wacu *WebAuthnChallengeUpdate) SetUser(u *User) *WebAuthnChallengeUpdate {
	return wacu.SetUserID(u.ID)
}

// Mutation returns the WebAuthnChallengeMutation object of the builder.
func (wacu *WebAuthnChallengeUpdate) Mutation() *WebAuthnChallengeMutation {
	return wacu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (wacu *WebAuthnChallengeUpdate) ClearUser() *WebAuthnChallengeUpdate {
	wacu.mutation.ClearUser()
	return wacu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wacu *WebAuthnChallengeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wacu.sqlSave, wacu.mutation, wacu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wacu *WebAuthnChallengeUpdate) SaveX(ctx context.Context) int {
	affected, err := wacu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wacu *WebAuthnChallengeUpdate) Exec(ctx context.Context) error {
	_, err := wacu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wacu *WebAuthnChallengeUpdate) ExecX(ctx context.Context) {
	if err := wacu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wacu *WebAuthnChallengeUpdate) check() error {
	if v, ok := wacu.mutation.SessionData(); ok {
		if err := webauthnchallenge.SessionDataValidator(v); err != nil {
			return &ValidationError{Name: "session_data", err: fmt.Errorf(`ent: validator failed for field "WebAuthnChallenge.session_data": %w`, err)}
		}
	}
	if v, ok := wacu.mutation.Kind(); ok {
		if err := webauthnchallenge.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "WebAuthnChallenge.kind": %w`, err)}
		}
	}
	if _, ok := wacu.mutation.UserID(); wacu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "WebAuthnChallenge.user"`)
	}
	return nil
}

func (wacu *WebAuthnChallengeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wacu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(webauthnchallenge.Table, webauthnchallenge.Columns, sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt))
	if ps := wacu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wacu.mutation.NonceHash(); ok {
		_spec.SetField(webauthnchallenge.FieldNonceHash, field.TypeString, value)
	}
	if value, ok := wacu.mutation.SessionData(); ok {
		_spec.SetField(webauthnchallenge.FieldSessionData, field.TypeString, value)
	}
	if value, ok := wacu.mutation.Kind(); ok {
		_spec.SetField(webauthnchallenge.FieldKind, field.TypeEnum, value)
	}
	if value, ok := wacu.mutation.ExpiresAt(); ok {
		_spec.SetField(webauthnchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if wacu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthnchallenge.UserTable,
			Columns: []string{webauthnchallenge.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wacu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthnchallenge.UserTable,
			Columns: []string{webauthnchallenge.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wacu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webauthnchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wacu.mutation.done = true
	return n, nil
}

// WebAuthnChallengeUpdateOne is the builder for updating a single WebAuthnChallenge entity.
type WebAuthnChallengeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebAuthnChallengeMutation
}

// SetNonceHash sets the "nonce_hash" field.
func (wacuo *WebAuthnChallengeUpdateOne) SetNonceHash(s string) *WebAuthnChallengeUpdateOne {
	wacuo.mutation.SetNonceHash(s)
	return wacuo
}

// SetNillableNonceHash sets the "nonce_hash" field if the given value is not nil.
func (wacuo *WebAuthnChallengeUpdateOne) SetNillableNonceHash(s *string) *WebAuthnChallengeUpdateOne {
	if s != nil {
		wacuo.SetNonceHash(*s)
	}
	return wacuo
}

// SetSessionData sets the "session_data" field.
func (wacuo *WebAuthnChallengeUpdateOne) SetSessionData(s string) *WebAuthnChallengeUpdateOne {
	wacuo.mutation.SetSessionData(s)
	return wacuo
}

// SetNillableSessionData sets the "session_data" field if the given value is not nil.
func (wacuo *WebAuthnChallengeUpdateOne) SetNillableSessionData(s *string) *WebAuthnChallengeUpdateOne {
	if s != nil {
		wacuo.SetSessionData(*s)
	}
	return wacuo
}

// SetKind sets the "kind" field.
func (wacuo *WebAuthnChallengeUpdateOne) SetKind(w webauthnchallenge.Kind) *WebAuthnChallengeUpdateOne {
	wacuo.mutation.SetKind(w)
	return wacuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (wacuo *WebAuthnChallengeUpdateOne) SetNillableKind(w *webauthnchallenge.Kind) *WebAuthnChallengeUpdateOne {
	if w != nil {
		wacuo.SetKind(*w)
	}
	return wacuo
}

// SetExpiresAt sets the "expires_at" field.
func (wacuo *WebAuthnChallengeUpdateOne) SetExpiresAt(t time.Time) *WebAuthnChallengeUpdateOne {
	wacuo.mutation.SetExpiresAt(t)
	return wacuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (wacuo *WebAuthnChallengeUpdateOne) SetNillableExpiresAt(t *time.Time) *WebAuthnChallengeUpdateOne {
	if t != nil {
		wacuo.SetExpiresAt(*t)
	}
	return wacuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (wacuo *WebAuthnChallengeUpdateOne) SetUserID(id int) *WebAuthnChallengeUpdateOne {
	wacuo.mutation.SetUserID(id)
	return wacuo
}

// SetUser sets the "user" edge to the User entity.
func (wacuo *WebAuthnChallengeUpdateOne) SetUser(u *User) *WebAuthnChallengeUpdateOne {
	return wacuo.SetUserID(u.ID)
}

// Mutation returns the WebAuthnChallengeMutation object of the builder.
func (wacuo *WebAuthnChallengeUpdateOne) Mutation() *WebAuthnChallengeMutation {
	return wacuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (wacuo *WebAuthnChallengeUpdateOne) ClearUser() *WebAuthnChallengeUpdateOne {
	wacuo.mutation.ClearUser()
	return wacuo
}

// Where appends a list predicates to the WebAuthnChallengeUpdate builder.
func (wacuo *WebAuthnChallengeUpdateOne) Where(ps ...predicate.WebAuthnChallenge) *WebAuthnChallengeUpdateOne {
	wacuo.mutation.Where(ps...)
	return wacuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wacuo *WebAuthnChallengeUpdateOne) Select(field string, fields ...string) *WebAuthnChallengeUpdateOne {
	wacuo.fields = append([]string{field}, fields...)
	return wacuo
}

// Save executes the query and returns the updated WebAuthnChallenge entity.
func (wacuo *WebAuthnChallengeUpdateOne) Save(ctx context.Context) (*WebAuthnChallenge, error) {
	return withHooks(ctx, wacuo.sqlSave, wacuo.mutation, wacuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wacuo *WebAuthnChallengeUpdateOne) SaveX(ctx context.Context) *WebAuthnChallenge {
	node, err := wacuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wacuo *WebAuthnChallengeUpdateOne) Exec(ctx context.Context) error {
	_, err := wacuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wacuo *WebAuthnChallengeUpdateOne) ExecX(ctx context.Context) {
	if err := wacuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wacuo *WebAuthnChallengeUpdateOne) check() error {
	if v, ok := wacuo.mutation.SessionData(); ok {
		if err := webauthnchallenge.SessionDataValidator(v); err != nil {
			return &ValidationError{Name: "session_data", err: fmt.Errorf(`ent: validator failed for field "WebAuthnChallenge.session_data": %w`, err)}
		}
	}
	if v, ok := wacuo.mutation.Kind(); ok {
		if err := webauthnchallenge.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "WebAuthnChallenge.kind": %w`, err)}
		}
	}
	if _, ok := wacuo.mutation.UserID(); wacuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "WebAuthnChallenge.user"`)
	}
	return nil
}

func (wacuo *WebAuthnChallengeUpdateOne) sqlSave(ctx context.Context) (_node *WebAuthnChallenge, err error) {
	if err := wacuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webauthnchallenge.Table, webauthnchallenge.Columns, sqlgraph.NewFieldSpec(webauthnchallenge.FieldID, field.TypeInt))
	id, ok := wacuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebAuthnChallenge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wacuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webauthnchallenge.FieldID)
		for _, f := range fields {
			if !webauthnchallenge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webauthnchallenge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wacuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wacuo.mutation.NonceHash(); ok {
		_spec.SetField(webauthnchallenge.FieldNonceHash, field.TypeString, value)
	}
	if value, ok := wacuo.mutation.SessionData(); ok {
		_spec.SetField(webauthnchallenge.FieldSessionData, field.TypeString, value)
	}
	if value, ok := wacuo.mutation.Kind(); ok {
		_spec.SetField(webauthnchallenge.FieldKind, field.TypeEnum, value)
	}
	if value, ok := wacuo.mutation.ExpiresAt(); ok {
		_spec.SetField(webauthnchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if wacuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthnchallenge.UserTable,
			Columns: []string{webauthnchallenge.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wacuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webauthnchallenge.UserTable,
			Columns: []string{webauthnchallenge.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebAuthnChallenge{config: wacuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wacuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webauthnchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wacuo.mutation.done = true
	return _node, nil
}
