// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"naust/daemon/internal/store/ent/tenant"
	"naust/daemon/internal/store/ent/webdomain"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WebDomain is the model entity for the WebDomain schema.
type WebDomain struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// Hsts holds the value of the "hsts" field.
	Hsts webdomain.Hsts `json:"hsts,omitempty"`
	// ServeStatic holds the value of the "serve_static" field.
	ServeStatic bool `json:"serve_static,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WebDomainQuery when eager-loading is set.
	Edges              WebDomainEdges `json:"edges"`
	tenant_web_domains *int
	selectValues       sql.SelectValues
}

// WebDomainEdges holds the relations/edges for other nodes in the graph.
type WebDomainEdges struct {
	// Rules holds the value of the rules edge.
	Rules []*WebRule `json:"rules,omitempty"`
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RulesOrErr returns the Rules value or an error if the edge
// was not loaded in eager-loading.
func (e WebDomainEdges) RulesOrErr() ([]*WebRule, error) {
	if e.loadedTypes[0] {
		return e.Rules, nil
	}
	return nil, &NotLoadedError{edge: "rules"}
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WebDomainEdges) TenantOrErr() (*Tenant, error) {
	if e.loadedTypes[1] {
		if e.Tenant == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: tenant.Label}
		}
		return e.Tenant, nil
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebDomain) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webdomain.FieldServeStatic:
			values[i] = new(sql.NullBool)
		case webdomain.FieldID:
			values[i] = new(sql.NullInt64)
		case webdomain.FieldDomain, webdomain.FieldHsts:
			values[i] = new(sql.NullString)
		case webdomain.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case webdomain.ForeignKeys[0]: // tenant_web_domains
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebDomain fields.
func (wd *WebDomain) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webdomain.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			wd.ID = int(value.Int64)
		case webdomain.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				wd.Domain = value.String
			}
		case webdomain.FieldHsts:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hsts", values[i])
			} else if value.Valid {
				wd.Hsts = webdomain.Hsts(value.String)
			}
		case webdomain.FieldServeStatic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field serve_static", values[i])
			} else if value.Valid {
				wd.ServeStatic = value.Bool
			}
		case webdomain.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wd.CreatedAt = value.Time
			}
		case webdomain.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_web_domains", value)
			} else if value.Valid {
				wd.tenant_web_domains = new(int)
				*wd.tenant_web_domains = int(value.Int64)
			}
		default:
			wd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebDomain.
// This includes values selected through modifiers, order, etc.
func (wd *WebDomain) Value(name string) (ent.Value, error) {
	return wd.selectValues.Get(name)
}

// QueryRules queries the "rules" edge of the WebDomain entity.
func (wd *WebDomain) QueryRules() *WebRuleQuery {
	return NewWebDomainClient(wd.config).QueryRules(wd)
}

// QueryTenant queries the "tenant" edge of the WebDomain entity.
func (wd *WebDomain) QueryTenant() *TenantQuery {
	return NewWebDomainClient(wd.config).QueryTenant(wd)
}

// Update returns a builder for updating this WebDomain.
// Note that you need to call WebDomain.Unwrap() before calling this method if this WebDomain
// was returned from a transaction, and the transaction was committed or rolled back.
func (wd *WebDomain) Update() *WebDomainUpdateOne {
	return NewWebDomainClient(wd.config).UpdateOne(wd)
}

// Unwrap unwraps the WebDomain entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wd *WebDomain) Unwrap() *WebDomain {
	_tx, ok := wd.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebDomain is not a transactional entity")
	}
	wd.config.driver = _tx.drv
	return wd
}

// String implements the fmt.Stringer.
func (wd *WebDomain) String() string {
	var builder strings.Builder
	builder.WriteString("WebDomain(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wd.ID))
	builder.WriteString("domain=")
	builder.WriteString(wd.Domain)
	builder.WriteString(", ")
	builder.WriteString("hsts=")
	builder.WriteString(fmt.Sprintf("%v", wd.Hsts))
	builder.WriteString(", ")
	builder.WriteString("serve_static=")
	builder.WriteString(fmt.Sprintf("%v", wd.ServeStatic))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(wd.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WebDomains is a parsable slice of WebDomain.
type WebDomains []*WebDomain
