// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/webdomain"
	"naust/daemon/internal/store/ent/webrule"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebRuleQuery is the builder for querying WebRule entities.
type WebRuleQuery struct {
	config
	ctx        *QueryContext
	order      []webrule.OrderOption
	inters     []Interceptor
	predicates []predicate.WebRule
	withDomain *WebDomainQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WebRuleQuery builder.
func (wrq *WebRuleQuery) Where(ps ...predicate.WebRule) *WebRuleQuery {
	wrq.predicates = append(wrq.predicates, ps...)
	return wrq
}

// Limit the number of records to be returned by this query.
func (wrq *WebRuleQuery) Limit(limit int) *WebRuleQuery {
	wrq.ctx.Limit = &limit
	return wrq
}

// Offset to start from.
func (wrq *WebRuleQuery) Offset(offset int) *WebRuleQuery {
	wrq.ctx.Offset = &offset
	return wrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wrq *WebRuleQuery) Unique(unique bool) *WebRuleQuery {
	wrq.ctx.Unique = &unique
	return wrq
}

// Order specifies how the records should be ordered.
func (wrq *WebRuleQuery) Order(o ...webrule.OrderOption) *WebRuleQuery {
	wrq.order = append(wrq.order, o...)
	return wrq
}

// QueryDomain chains the current query on the "domain" edge.
func (wrq *WebRuleQuery) QueryDomain() *WebDomainQuery {
	query := (&WebDomainClient{config: wrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(webrule.Table, webrule.FieldID, selector),
			sqlgraph.To(webdomain.Table, webdomain.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, webrule.DomainTable, webrule.DomainColumn),
		)
		fromU = sqlgraph.SetNeighbors(wrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WebRule entity from the query.
// Returns a *NotFoundError when no WebRule was found.
func (wrq *WebRuleQuery) First(ctx context.Context) (*WebRule, error) {
	nodes, err := wrq.Limit(1).All(setContextOp(ctx, wrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{webrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wrq *WebRuleQuery) FirstX(ctx context.Context) *WebRule {
	node, err := wrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WebRule ID from the query.
// Returns a *NotFoundError when no WebRule ID was found.
func (wrq *WebRuleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wrq.Limit(1).IDs(setContextOp(ctx, wrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{webrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wrq *WebRuleQuery) FirstIDX(ctx context.Context) int {
	id, err := wrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WebRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WebRule entity is found.
// Returns a *NotFoundError when no WebRule entities are found.
func (wrq *WebRuleQuery) Only(ctx context.Context) (*WebRule, error) {
	nodes, err := wrq.Limit(2).All(setContextOp(ctx, wrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{webrule.Label}
	default:
		return nil, &NotSingularError{webrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wrq *WebRuleQuery) OnlyX(ctx context.Context) *WebRule {
	node, err := wrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WebRule ID in the query.
// Returns a *NotSingularError when more than one WebRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (wrq *WebRuleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wrq.Limit(2).IDs(setContextOp(ctx, wrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{webrule.Label}
	default:
		err = &NotSingularError{webrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wrq *WebRuleQuery) OnlyIDX(ctx context.Context) int {
	id, err := wrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WebRules.
func (wrq *WebRuleQuery) All(ctx context.Context) ([]*WebRule, error) {
	ctx = setContextOp(ctx, wrq.ctx, "All")
	if err := wrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WebRule, *WebRuleQuery]()
	return withInterceptors[[]*WebRule](ctx, wrq, qr, wrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wrq *WebRuleQuery) AllX(ctx context.Context) []*WebRule {
	nodes, err := wrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WebRule IDs.
func (wrq *WebRuleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wrq.ctx.Unique == nil && wrq.path != nil {
		wrq.Unique(true)
	}
	ctx = setContextOp(ctx, wrq.ctx, "IDs")
	if err = wrq.Select(webrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wrq *WebRuleQuery) IDsX(ctx context.Context) []int {
	ids, err := wrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wrq *WebRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wrq.ctx, "Count")
	if err := wrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wrq, querierCount[*WebRuleQuery](), wrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wrq *WebRuleQuery) CountX(ctx context.Context) int {
	count, err := wrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wrq *WebRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wrq.ctx, "Exist")
	switch _, err := wrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wrq *WebRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := wrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WebRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wrq *WebRuleQuery) Clone() *WebRuleQuery {
	if wrq == nil {
		return nil
	}
	return &WebRuleQuery{
		config:     wrq.config,
		ctx:        wrq.ctx.Clone(),
		order:      append([]webrule.OrderOption{}, wrq.order...),
		inters:     append([]Interceptor{}, wrq.inters...),
		predicates: append([]predicate.WebRule{}, wrq.predicates...),
		withDomain: wrq.withDomain.Clone(),
		// clone intermediate query.
		sql:  wrq.sql.Clone(),
		path: wrq.path,
	}
}

// WithDomain tells the query-builder to eager-load the nodes that are connected to
// the "domain" edge. The optional arguments are used to configure the query builder of the edge.
func (wrq *WebRuleQuery) WithDomain(opts ...func(*WebDomainQuery)) *WebRuleQuery {
	query := (&WebDomainClient{config: wrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wrq.withDomain = query
	return wrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Kind webrule.Kind `json:"kind,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WebRule.Query().
//		GroupBy(webrule.FieldKind).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wrq *WebRuleQuery) GroupBy(field string, fields ...string) *WebRuleGroupBy {
	wrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WebRuleGroupBy{build: wrq}
	grbuild.flds = &wrq.ctx.Fields
	grbuild.label = webrule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Kind webrule.Kind `json:"kind,omitempty"`
//	}
//
//	client.WebRule.Query().
//		Select(webrule.FieldKind).
//		Scan(ctx, &v)
func (wrq *WebRuleQuery) Select(fields ...string) *WebRuleSelect {
	wrq.ctx.Fields = append(wrq.ctx.Fields, fields...)
	sbuild := &WebRuleSelect{WebRuleQuery: wrq}
	sbuild.label = webrule.Label
	sbuild.flds, sbuild.scan = &wrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WebRuleSelect configured with the given aggregations.
func (wrq *WebRuleQuery) Aggregate(fns ...AggregateFunc) *WebRuleSelect {
	return wrq.Select().Aggregate(fns...)
}

func (wrq *WebRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wrq); err != nil {
				return err
			}
		}
	}
	for _, f := range wrq.ctx.Fields {
		if !webrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wrq.path != nil {
		prev, err := wrq.path(ctx)
		if err != nil {
			return err
		}
		wrq.sql = prev
	}
	return nil
}

func (wrq *WebRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WebRule, error) {
	var (
		nodes       = []*WebRule{}
		withFKs     = wrq.withFKs
		_spec       = wrq.querySpec()
		loadedTypes = [1]bool{
			wrq.withDomain != nil,
		}
	)
	if wrq.withDomain != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, webrule.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WebRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WebRule{config: wrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wrq.withDomain; query != nil {
		if err := wrq.loadDomain(ctx, query, nodes, nil,
			func(n *WebRule, e *WebDomain) { n.Edges.Domain = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wrq *WebRuleQuery) loadDomain(ctx context.Context, query *WebDomainQuery, nodes []*WebRule, init func(*WebRule), assign func(*WebRule, *WebDomain)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WebRule)
	for i := range nodes {
		if nodes[i].web_domain_rules == nil {
			continue
		}
		fk := *nodes[i].web_domain_rules
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(webdomain.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "web_domain_rules" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (wrq *WebRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wrq.querySpec()
	_spec.Node.Columns = wrq.ctx.Fields
	if len(wrq.ctx.Fields) > 0 {
		_spec.Unique = wrq.ctx.Unique != nil && *wrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wrq.driver, _spec)
}

func (wrq *WebRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(webrule.Table, webrule.Columns, sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt))
	_spec.From = wrq.sql
	if unique := wrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wrq.path != nil {
		_spec.Unique = true
	}
	if fields := wrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webrule.FieldID)
		for i := range fields {
			if fields[i] != webrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wrq *WebRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wrq.driver.Dialect())
	t1 := builder.Table(webrule.Table)
	columns := wrq.ctx.Fields
	if len(columns) == 0 {
		columns = webrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wrq.sql != nil {
		selector = wrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wrq.ctx.Unique != nil && *wrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wrq.predicates {
		p(selector)
	}
	for _, p := range wrq.order {
		p(selector)
	}
	if offset := wrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WebRuleGroupBy is the group-by builder for WebRule entities.
type WebRuleGroupBy struct {
	selector
	build *WebRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wrgb *WebRuleGroupBy) Aggregate(fns ...AggregateFunc) *WebRuleGroupBy {
	wrgb.fns = append(wrgb.fns, fns...)
	return wrgb
}

// Scan applies the selector query and scans the result into the given value.
func (wrgb *WebRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrgb.build.ctx, "GroupBy")
	if err := wrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebRuleQuery, *WebRuleGroupBy](ctx, wrgb.build, wrgb, wrgb.build.inters, v)
}

func (wrgb *WebRuleGroupBy) sqlScan(ctx context.Context, root *WebRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wrgb.fns))
	for _, fn := range wrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wrgb.flds)+len(wrgb.fns))
		for _, f := range *wrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WebRuleSelect is the builder for selecting fields of WebRule entities.
type WebRuleSelect struct {
	*WebRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wrs *WebRuleSelect) Aggregate(fns ...AggregateFunc) *WebRuleSelect {
	wrs.fns = append(wrs.fns, fns...)
	return wrs
}

// Scan applies the selector query and scans the result into the given value.
func (wrs *WebRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wrs.ctx, "Select")
	if err := wrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebRuleQuery, *WebRuleSelect](ctx, wrs.WebRuleQuery, wrs, wrs.inters, v)
}

func (wrs *WebRuleSelect) sqlScan(ctx context.Context, root *WebRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wrs.fns))
	for _, fn := range wrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
