// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/webdomain"
	"naust/daemon/internal/store/ent/webrule"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebRuleCreate is the builder for creating a WebRule entity.
type WebRuleCreate struct {
	config
	mutation *WebRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (wrc *WebRuleCreate) SetKind(w webrule.Kind) *WebRuleCreate {
	wrc.mutation.SetKind(w)
	return wrc
}

// SetPath sets the "path" field.
func (wrc *WebRuleCreate) SetPath(s string) *WebRuleCreate {
	wrc.mutation.SetPath(s)
	return wrc
}

// SetTarget sets the "target" field.
func (wrc *WebRuleCreate) SetTarget(s string) *WebRuleCreate {
	wrc.mutation.SetTarget(s)
	return wrc
}

// SetPassHostHeader sets the "pass_host_header" field.
func (wrc *WebRuleCreate) SetPassHostHeader(b bool) *WebRuleCreate {
	wrc.mutation.SetPassHostHeader(b)
	return wrc
}

// SetNillablePassHostHeader sets the "pass_host_header" field if the given value is not nil.
func (wrc *WebRuleCreate) SetNillablePassHostHeader(b *bool) *WebRuleCreate {
	if b != nil {
		wrc.SetPassHostHeader(*b)
	}
	return wrc
}

// SetNoProxyRedirect sets the "no_proxy_redirect" field.
func (wrc *WebRuleCreate) SetNoProxyRedirect(b bool) *WebRuleCreate {
	wrc.mutation.SetNoProxyRedirect(b)
	return wrc
}

// SetNillableNoProxyRedirect sets the "no_proxy_redirect" field if the given value is not nil.
func (wrc *WebRuleCreate) SetNillableNoProxyRedirect(b *bool) *WebRuleCreate {
	if b != nil {
		wrc.SetNoProxyRedirect(*b)
	}
	return wrc
}

// SetFrameSameOrigin sets the "frame_same_origin" field.
func (wrc *WebRuleCreate) SetFrameSameOrigin(b bool) *WebRuleCreate {
	wrc.mutation.SetFrameSameOrigin(b)
	return wrc
}

// SetNillableFrameSameOrigin sets the "frame_same_origin" field if the given value is not nil.
func (wrc *WebRuleCreate) SetNillableFrameSameOrigin(b *bool) *WebRuleCreate {
	if b != nil {
		wrc.SetFrameSameOrigin(*b)
	}
	return wrc
}

// SetWebSockets sets the "web_sockets" field.
func (wrc *WebRuleCreate) SetWebSockets(b bool) *WebRuleCreate {
	wrc.mutation.SetWebSockets(b)
	return wrc
}

// SetNillableWebSockets sets the "web_sockets" field if the given value is not nil.
func (wrc *WebRuleCreate) SetNillableWebSockets(b *bool) *WebRuleCreate {
	if b != nil {
		wrc.SetWebSockets(*b)
	}
	return wrc
}

// SetDomainID sets the "domain" edge to the WebDomain entity by ID.
func (wrc *WebRuleCreate) SetDomainID(id int) *WebRuleCreate {
	wrc.mutation.SetDomainID(id)
	return wrc
}

// SetDomain sets the "domain" edge to the WebDomain entity.
func (wrc *WebRuleCreate) SetDomain(w *WebDomain) *WebRuleCreate {
	return wrc.SetDomainID(w.ID)
}

// Mutation returns the WebRuleMutation object of the builder.
func (wrc *WebRuleCreate) Mutation() *WebRuleMutation {
	return wrc.mutation
}

// Save creates the WebRule in the database.
func (wrc *WebRuleCreate) Save(ctx context.Context) (*WebRule, error) {
	wrc.defaults()
	return withHooks(ctx, wrc.sqlSave, wrc.mutation, wrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wrc *WebRuleCreate) SaveX(ctx context.Context) *WebRule {
	v, err := wrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wrc *WebRuleCreate) Exec(ctx context.Context) error {
	_, err := wrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wrc *WebRuleCreate) ExecX(ctx context.Context) {
	if err := wrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wrc *WebRuleCreate) defaults() {
	if _, ok := wrc.mutation.PassHostHeader(); !ok {
		v := webrule.DefaultPassHostHeader
		wrc.mutation.SetPassHostHeader(v)
	}
	if _, ok := wrc.mutation.NoProxyRedirect(); !ok {
		v := webrule.DefaultNoProxyRedirect
		wrc.mutation.SetNoProxyRedirect(v)
	}
	if _, ok := wrc.mutation.FrameSameOrigin(); !ok {
		v := webrule.DefaultFrameSameOrigin
		wrc.mutation.SetFrameSameOrigin(v)
	}
	if _, ok := wrc.mutation.WebSockets(); !ok {
		v := webrule.DefaultWebSockets
		wrc.mutation.SetWebSockets(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wrc *WebRuleCreate) check() error {
	if _, ok := wrc.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "WebRule.kind"`)}
	}
	if v, ok := wrc.mutation.Kind(); ok {
		if err := webrule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "WebRule.kind": %w`, err)}
		}
	}
	if _, ok := wrc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "WebRule.path"`)}
	}
	if v, ok := wrc.mutation.Path(); ok {
		if err := webrule.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "WebRule.path": %w`, err)}
		}
	}
	if _, ok := wrc.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "WebRule.target"`)}
	}
	if v, ok := wrc.mutation.Target(); ok {
		if err := webrule.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "WebRule.target": %w`, err)}
		}
	}
	if _, ok := wrc.mutation.PassHostHeader(); !ok {
		return &ValidationError{Name: "pass_host_header", err: errors.New(`ent: missing required field "WebRule.pass_host_header"`)}
	}
	if _, ok := wrc.mutation.NoProxyRedirect(); !ok {
		return &ValidationError{Name: "no_proxy_redirect", err: errors.New(`ent: missing required field "WebRule.no_proxy_redirect"`)}
	}
	if _, ok := wrc.mutation.FrameSameOrigin(); !ok {
		return &ValidationError{Name: "frame_same_origin", err: errors.New(`ent: missing required field "WebRule.frame_same_origin"`)}
	}
	if _, ok := wrc.mutation.WebSockets(); !ok {
		return &ValidationError{Name: "web_sockets", err: errors.New(`ent: missing required field "WebRule.web_sockets"`)}
	}
	if _, ok := wrc.mutation.DomainID(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required edge "WebRule.domain"`)}
	}
	return nil
}

func (wrc *WebRuleCreate) sqlSave(ctx context.Context) (*WebRule, error) {
	if err := wrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	wrc.mutation.id = &_node.ID
	wrc.mutation.done = true
	return _node, nil
}

func (wrc *WebRuleCreate) createSpec() (*WebRule, *sqlgraph.CreateSpec) {
	var (
		_node = &WebRule{config: wrc.config}
		_spec = sqlgraph.NewCreateSpec(webrule.Table, sqlgraph.NewFieldSpec(webrule.FieldID, field.TypeInt))
	)
	_spec.OnConflict = wrc.conflict
	if value, ok := wrc.mutation.Kind(); ok {
		_spec.SetField(webrule.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := wrc.mutation.Path(); ok {
		_spec.SetField(webrule.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := wrc.mutation.Target(); ok {
		_spec.SetField(webrule.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := wrc.mutation.PassHostHeader(); ok {
		_spec.SetField(webrule.FieldPassHostHeader, field.TypeBool, value)
		_node.PassHostHeader = value
	}
	if value, ok := wrc.mutation.NoProxyRedirect(); ok {
		_spec.SetField(webrule.FieldNoProxyRedirect, field.TypeBool, value)
		_node.NoProxyRedirect = value
	}
	if value, ok := wrc.mutation.FrameSameOrigin(); ok {
		_spec.SetField(webrule.FieldFrameSameOrigin, field.TypeBool, value)
		_node.FrameSameOrigin = value
	}
	if value, ok := wrc.mutation.WebSockets(); ok {
		_spec.SetField(webrule.FieldWebSockets, field.TypeBool, value)
		_node.WebSockets = value
	}
	if nodes := wrc.mutation.DomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webrule.DomainTable,
			Columns: []string{webrule.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.web_domain_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebRule.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebRuleUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (wrc *WebRuleCreate) OnConflict(opts ...sql.ConflictOption) *WebRuleUpsertOne {
	wrc.conflict = opts
	return &WebRuleUpsertOne{
		create: wrc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (wrc *WebRuleCreate) OnConflictColumns(columns ...string) *WebRuleUpsertOne {
	wrc.conflict = append(wrc.conflict, sql.ConflictColumns(columns...))
	return &WebRuleUpsertOne{
		create: wrc,
	}
}

type (
	// WebRuleUpsertOne is the builder for "upsert"-ing
	//  one WebRule node.
	WebRuleUpsertOne struct {
		create *WebRuleCreate
	}

	// WebRuleUpsert is the "OnConflict" setter.
	WebRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *WebRuleUpsert) SetKind(v webrule.Kind) *WebRuleUpsert {
	u.Set(webrule.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdateKind() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldKind)
	return u
}

// SetPath sets the "path" field.
func (u *WebRuleUpsert) SetPath(v string) *WebRuleUpsert {
	u.Set(webrule.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdatePath() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldPath)
	return u
}

// SetTarget sets the "target" field.
func (u *WebRuleUpsert) SetTarget(v string) *WebRuleUpsert {
	u.Set(webrule.FieldTarget, v)
	return u
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdateTarget() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldTarget)
	return u
}

// SetPassHostHeader sets the "pass_host_header" field.
func (u *WebRuleUpsert) SetPassHostHeader(v bool) *WebRuleUpsert {
	u.Set(webrule.FieldPassHostHeader, v)
	return u
}

// UpdatePassHostHeader sets the "pass_host_header" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdatePassHostHeader() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldPassHostHeader)
	return u
}

// SetNoProxyRedirect sets the "no_proxy_redirect" field.
func (u *WebRuleUpsert) SetNoProxyRedirect(v bool) *WebRuleUpsert {
	u.Set(webrule.FieldNoProxyRedirect, v)
	return u
}

// UpdateNoProxyRedirect sets the "no_proxy_redirect" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdateNoProxyRedirect() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldNoProxyRedirect)
	return u
}

// SetFrameSameOrigin sets the "frame_same_origin" field.
func (u *WebRuleUpsert) SetFrameSameOrigin(v bool) *WebRuleUpsert {
	u.Set(webrule.FieldFrameSameOrigin, v)
	return u
}

// UpdateFrameSameOrigin sets the "frame_same_origin" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdateFrameSameOrigin() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldFrameSameOrigin)
	return u
}

// SetWebSockets sets the "web_sockets" field.
func (u *WebRuleUpsert) SetWebSockets(v bool) *WebRuleUpsert {
	u.Set(webrule.FieldWebSockets, v)
	return u
}

// UpdateWebSockets sets the "web_sockets" field to the value that was provided on create.
func (u *WebRuleUpsert) UpdateWebSockets() *WebRuleUpsert {
	u.SetExcluded(webrule.FieldWebSockets)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebRuleUpsertOne) UpdateNewValues() *WebRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebRuleUpsertOne) Ignore() *WebRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebRuleUpsertOne) DoNothing() *WebRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebRuleCreate.OnConflict
// documentation for more info.
func (u *WebRuleUpsertOne) Update(set func(*WebRuleUpsert)) *WebRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *WebRuleUpsertOne) SetKind(v webrule.Kind) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdateKind() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateKind()
	})
}

// SetPath sets the "path" field.
func (u *WebRuleUpsertOne) SetPath(v string) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdatePath() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdatePath()
	})
}

// SetTarget sets the "target" field.
func (u *WebRuleUpsertOne) SetTarget(v string) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdateTarget() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateTarget()
	})
}

// SetPassHostHeader sets the "pass_host_header" field.
func (u *WebRuleUpsertOne) SetPassHostHeader(v bool) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetPassHostHeader(v)
	})
}

// UpdatePassHostHeader sets the "pass_host_header" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdatePassHostHeader() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdatePassHostHeader()
	})
}

// SetNoProxyRedirect sets the "no_proxy_redirect" field.
func (u *WebRuleUpsertOne) SetNoProxyRedirect(v bool) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetNoProxyRedirect(v)
	})
}

// UpdateNoProxyRedirect sets the "no_proxy_redirect" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdateNoProxyRedirect() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateNoProxyRedirect()
	})
}

// SetFrameSameOrigin sets the "frame_same_origin" field.
func (u *WebRuleUpsertOne) SetFrameSameOrigin(v bool) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetFrameSameOrigin(v)
	})
}

// UpdateFrameSameOrigin sets the "frame_same_origin" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdateFrameSameOrigin() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateFrameSameOrigin()
	})
}

// SetWebSockets sets the "web_sockets" field.
func (u *WebRuleUpsertOne) SetWebSockets(v bool) *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetWebSockets(v)
	})
}

// UpdateWebSockets sets the "web_sockets" field to the value that was provided on create.
func (u *WebRuleUpsertOne) UpdateWebSockets() *WebRuleUpsertOne {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateWebSockets()
	})
}

// Exec executes the query.
func (u *WebRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebRuleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebRuleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebRuleCreateBulk is the builder for creating many WebRule entities in bulk.
type WebRuleCreateBulk struct {
	config
	err      error
	builders []*WebRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the WebRule entities in the database.
func (wrcb *WebRuleCreateBulk) Save(ctx context.Context) ([]*WebRule, error) {
	if wrcb.err != nil {
		return nil, wrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wrcb.builders))
	nodes := make([]*WebRule, len(wrcb.builders))
	mutators := make([]Mutator, len(wrcb.builders))
	for i := range wrcb.builders {
		func(i int, root context.Context) {
			builder := wrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = wrcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wrcb *WebRuleCreateBulk) SaveX(ctx context.Context) []*WebRule {
	v, err := wrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wrcb *WebRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := wrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wrcb *WebRuleCreateBulk) ExecX(ctx context.Context) {
	if err := wrcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebRuleUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (wrcb *WebRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebRuleUpsertBulk {
	wrcb.conflict = opts
	return &WebRuleUpsertBulk{
		create: wrcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (wrcb *WebRuleCreateBulk) OnConflictColumns(columns ...string) *WebRuleUpsertBulk {
	wrcb.conflict = append(wrcb.conflict, sql.ConflictColumns(columns...))
	return &WebRuleUpsertBulk{
		create: wrcb,
	}
}

// WebRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of WebRule nodes.
type WebRuleUpsertBulk struct {
	create *WebRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebRuleUpsertBulk) UpdateNewValues() *WebRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebRuleUpsertBulk) Ignore() *WebRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebRuleUpsertBulk) DoNothing() *WebRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebRuleCreateBulk.OnConflict
// documentation for more info.
func (u *WebRuleUpsertBulk) Update(set func(*WebRuleUpsert)) *WebRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *WebRuleUpsertBulk) SetKind(v webrule.Kind) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdateKind() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateKind()
	})
}

// SetPath sets the "path" field.
func (u *WebRuleUpsertBulk) SetPath(v string) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdatePath() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdatePath()
	})
}

// SetTarget sets the "target" field.
func (u *WebRuleUpsertBulk) SetTarget(v string) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdateTarget() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateTarget()
	})
}

// SetPassHostHeader sets the "pass_host_header" field.
func (u *WebRuleUpsertBulk) SetPassHostHeader(v bool) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetPassHostHeader(v)
	})
}

// UpdatePassHostHeader sets the "pass_host_header" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdatePassHostHeader() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdatePassHostHeader()
	})
}

// SetNoProxyRedirect sets the "no_proxy_redirect" field.
func (u *WebRuleUpsertBulk) SetNoProxyRedirect(v bool) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetNoProxyRedirect(v)
	})
}

// UpdateNoProxyRedirect sets the "no_proxy_redirect" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdateNoProxyRedirect() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateNoProxyRedirect()
	})
}

// SetFrameSameOrigin sets the "frame_same_origin" field.
func (u *WebRuleUpsertBulk) SetFrameSameOrigin(v bool) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetFrameSameOrigin(v)
	})
}

// UpdateFrameSameOrigin sets the "frame_same_origin" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdateFrameSameOrigin() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateFrameSameOrigin()
	})
}

// SetWebSockets sets the "web_sockets" field.
func (u *WebRuleUpsertBulk) SetWebSockets(v bool) *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.SetWebSockets(v)
	})
}

// UpdateWebSockets sets the "web_sockets" field to the value that was provided on create.
func (u *WebRuleUpsertBulk) UpdateWebSockets() *WebRuleUpsertBulk {
	return u.Update(func(s *WebRuleUpsert) {
		s.UpdateWebSockets()
	})
}

// Exec executes the query.
func (u *WebRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
