// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"naust/daemon/internal/store/ent/zoneserial"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ZoneSerialCreate is the builder for creating a ZoneSerial entity.
type ZoneSerialCreate struct {
	config
	mutation *ZoneSerialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetZone sets the "zone" field.
func (zsc *ZoneSerialCreate) SetZone(s string) *ZoneSerialCreate {
	zsc.mutation.SetZone(s)
	return zsc
}

// SetSerial sets the "serial" field.
func (zsc *ZoneSerialCreate) SetSerial(i int64) *ZoneSerialCreate {
	zsc.mutation.SetSerial(i)
	return zsc
}

// SetContentHash sets the "content_hash" field.
func (zsc *ZoneSerialCreate) SetContentHash(s string) *ZoneSerialCreate {
	zsc.mutation.SetContentHash(s)
	return zsc
}

// Mutation returns the ZoneSerialMutation object of the builder.
func (zsc *ZoneSerialCreate) Mutation() *ZoneSerialMutation {
	return zsc.mutation
}

// Save creates the ZoneSerial in the database.
func (zsc *ZoneSerialCreate) Save(ctx context.Context) (*ZoneSerial, error) {
	return withHooks(ctx, zsc.sqlSave, zsc.mutation, zsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (zsc *ZoneSerialCreate) SaveX(ctx context.Context) *ZoneSerial {
	v, err := zsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (zsc *ZoneSerialCreate) Exec(ctx context.Context) error {
	_, err := zsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (zsc *ZoneSerialCreate) ExecX(ctx context.Context) {
	if err := zsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (zsc *ZoneSerialCreate) check() error {
	if _, ok := zsc.mutation.Zone(); !ok {
		return &ValidationError{Name: "zone", err: errors.New(`ent: missing required field "ZoneSerial.zone"`)}
	}
	if v, ok := zsc.mutation.Zone(); ok {
		if err := zoneserial.ZoneValidator(v); err != nil {
			return &ValidationError{Name: "zone", err: fmt.Errorf(`ent: validator failed for field "ZoneSerial.zone": %w`, err)}
		}
	}
	if _, ok := zsc.mutation.Serial(); !ok {
		return &ValidationError{Name: "serial", err: errors.New(`ent: missing required field "ZoneSerial.serial"`)}
	}
	if v, ok := zsc.mutation.Serial(); ok {
		if err := zoneserial.SerialValidator(v); err != nil {
			return &ValidationError{Name: "serial", err: fmt.Errorf(`ent: validator failed for field "ZoneSerial.serial": %w`, err)}
		}
	}
	if _, ok := zsc.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "ZoneSerial.content_hash"`)}
	}
	if v, ok := zsc.mutation.ContentHash(); ok {
		if err := zoneserial.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "ZoneSerial.content_hash": %w`, err)}
		}
	}
	return nil
}

func (zsc *ZoneSerialCreate) sqlSave(ctx context.Context) (*ZoneSerial, error) {
	if err := zsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := zsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, zsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	zsc.mutation.id = &_node.ID
	zsc.mutation.done = true
	return _node, nil
}

func (zsc *ZoneSerialCreate) createSpec() (*ZoneSerial, *sqlgraph.CreateSpec) {
	var (
		_node = &ZoneSerial{config: zsc.config}
		_spec = sqlgraph.NewCreateSpec(zoneserial.Table, sqlgraph.NewFieldSpec(zoneserial.FieldID, field.TypeInt))
	)
	_spec.OnConflict = zsc.conflict
	if value, ok := zsc.mutation.Zone(); ok {
		_spec.SetField(zoneserial.FieldZone, field.TypeString, value)
		_node.Zone = value
	}
	if value, ok := zsc.mutation.Serial(); ok {
		_spec.SetField(zoneserial.FieldSerial, field.TypeInt64, value)
		_node.Serial = value
	}
	if value, ok := zsc.mutation.ContentHash(); ok {
		_spec.SetField(zoneserial.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ZoneSerial.Create().
//		SetZone(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZoneSerialUpsert) {
//			SetZone(v+v).
//		}).
//		Exec(ctx)
func (zsc *ZoneSerialCreate) OnConflict(opts ...sql.ConflictOption) *ZoneSerialUpsertOne {
	zsc.conflict = opts
	return &ZoneSerialUpsertOne{
		create: zsc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ZoneSerial.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (zsc *ZoneSerialCreate) OnConflictColumns(columns ...string) *ZoneSerialUpsertOne {
	zsc.conflict = append(zsc.conflict, sql.ConflictColumns(columns...))
	return &ZoneSerialUpsertOne{
		create: zsc,
	}
}

type (
	// ZoneSerialUpsertOne is the builder for "upsert"-ing
	//  one ZoneSerial node.
	ZoneSerialUpsertOne struct {
		create *ZoneSerialCreate
	}

	// ZoneSerialUpsert is the "OnConflict" setter.
	ZoneSerialUpsert struct {
		*sql.UpdateSet
	}
)

// SetZone sets the "zone" field.
func (u *ZoneSerialUpsert) SetZone(v string) *ZoneSerialUpsert {
	u.Set(zoneserial.FieldZone, v)
	return u
}

// UpdateZone sets the "zone" field to the value that was provided on create.
func (u *ZoneSerialUpsert) UpdateZone() *ZoneSerialUpsert {
	u.SetExcluded(zoneserial.FieldZone)
	return u
}

// SetSerial sets the "serial" field.
func (u *ZoneSerialUpsert) SetSerial(v int64) *ZoneSerialUpsert {
	u.Set(zoneserial.FieldSerial, v)
	return u
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *ZoneSerialUpsert) UpdateSerial() *ZoneSerialUpsert {
	u.SetExcluded(zoneserial.FieldSerial)
	return u
}

// AddSerial adds v to the "serial" field.
func (u *ZoneSerialUpsert) AddSerial(v int64) *ZoneSerialUpsert {
	u.Add(zoneserial.FieldSerial, v)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *ZoneSerialUpsert) SetContentHash(v string) *ZoneSerialUpsert {
	u.Set(zoneserial.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *ZoneSerialUpsert) UpdateContentHash() *ZoneSerialUpsert {
	u.SetExcluded(zoneserial.FieldContentHash)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ZoneSerial.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ZoneSerialUpsertOne) UpdateNewValues() *ZoneSerialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ZoneSerial.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ZoneSerialUpsertOne) Ignore() *ZoneSerialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZoneSerialUpsertOne) DoNothing() *ZoneSerialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZoneSerialCreate.OnConflict
// documentation for more info.
func (u *ZoneSerialUpsertOne) Update(set func(*ZoneSerialUpsert)) *ZoneSerialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZoneSerialUpsert{UpdateSet: update})
	}))
	return u
}

// SetZone sets the "zone" field.
func (u *ZoneSerialUpsertOne) SetZone(v string) *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.SetZone(v)
	})
}

// UpdateZone sets the "zone" field to the value that was provided on create.
func (u *ZoneSerialUpsertOne) UpdateZone() *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.UpdateZone()
	})
}

// SetSerial sets the "serial" field.
func (u *ZoneSerialUpsertOne) SetSerial(v int64) *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.SetSerial(v)
	})
}

// AddSerial adds v to the "serial" field.
func (u *ZoneSerialUpsertOne) AddSerial(v int64) *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.AddSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *ZoneSerialUpsertOne) UpdateSerial() *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.UpdateSerial()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *ZoneSerialUpsertOne) SetContentHash(v string) *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *ZoneSerialUpsertOne) UpdateContentHash() *ZoneSerialUpsertOne {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.UpdateContentHash()
	})
}

// Exec executes the query.
func (u *ZoneSerialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZoneSerialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZoneSerialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ZoneSerialUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ZoneSerialUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ZoneSerialCreateBulk is the builder for creating many ZoneSerial entities in bulk.
type ZoneSerialCreateBulk struct {
	config
	err      error
	builders []*ZoneSerialCreate
	conflict []sql.ConflictOption
}

// Save creates the ZoneSerial entities in the database.
func (zscb *ZoneSerialCreateBulk) Save(ctx context.Context) ([]*ZoneSerial, error) {
	if zscb.err != nil {
		return nil, zscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(zscb.builders))
	nodes := make([]*ZoneSerial, len(zscb.builders))
	mutators := make([]Mutator, len(zscb.builders))
	for i := range zscb.builders {
		func(i int, root context.Context) {
			builder := zscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ZoneSerialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, zscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = zscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, zscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, zscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (zscb *ZoneSerialCreateBulk) SaveX(ctx context.Context) []*ZoneSerial {
	v, err := zscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (zscb *ZoneSerialCreateBulk) Exec(ctx context.Context) error {
	_, err := zscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (zscb *ZoneSerialCreateBulk) ExecX(ctx context.Context) {
	if err := zscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ZoneSerial.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZoneSerialUpsert) {
//			SetZone(v+v).
//		}).
//		Exec(ctx)
func (zscb *ZoneSerialCreateBulk) OnConflict(opts ...sql.ConflictOption) *ZoneSerialUpsertBulk {
	zscb.conflict = opts
	return &ZoneSerialUpsertBulk{
		create: zscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ZoneSerial.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (zscb *ZoneSerialCreateBulk) OnConflictColumns(columns ...string) *ZoneSerialUpsertBulk {
	zscb.conflict = append(zscb.conflict, sql.ConflictColumns(columns...))
	return &ZoneSerialUpsertBulk{
		create: zscb,
	}
}

// ZoneSerialUpsertBulk is the builder for "upsert"-ing
// a bulk of ZoneSerial nodes.
type ZoneSerialUpsertBulk struct {
	create *ZoneSerialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ZoneSerial.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ZoneSerialUpsertBulk) UpdateNewValues() *ZoneSerialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ZoneSerial.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ZoneSerialUpsertBulk) Ignore() *ZoneSerialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZoneSerialUpsertBulk) DoNothing() *ZoneSerialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZoneSerialCreateBulk.OnConflict
// documentation for more info.
func (u *ZoneSerialUpsertBulk) Update(set func(*ZoneSerialUpsert)) *ZoneSerialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZoneSerialUpsert{UpdateSet: update})
	}))
	return u
}

// SetZone sets the "zone" field.
func (u *ZoneSerialUpsertBulk) SetZone(v string) *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.SetZone(v)
	})
}

// UpdateZone sets the "zone" field to the value that was provided on create.
func (u *ZoneSerialUpsertBulk) UpdateZone() *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.UpdateZone()
	})
}

// SetSerial sets the "serial" field.
func (u *ZoneSerialUpsertBulk) SetSerial(v int64) *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.SetSerial(v)
	})
}

// AddSerial adds v to the "serial" field.
func (u *ZoneSerialUpsertBulk) AddSerial(v int64) *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.AddSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *ZoneSerialUpsertBulk) UpdateSerial() *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.UpdateSerial()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *ZoneSerialUpsertBulk) SetContentHash(v string) *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *ZoneSerialUpsertBulk) UpdateContentHash() *ZoneSerialUpsertBulk {
	return u.Update(func(s *ZoneSerialUpsert) {
		s.UpdateContentHash()
	})
}

// Exec executes the query.
func (u *ZoneSerialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ZoneSerialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZoneSerialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZoneSerialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
