// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"naust/daemon/internal/store/ent/predicate"
	"naust/daemon/internal/store/ent/zoneserial"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ZoneSerialDelete is the builder for deleting a ZoneSerial entity.
type ZoneSerialDelete struct {
	config
	hooks    []Hook
	mutation *ZoneSerialMutation
}

// Where appends a list predicates to the ZoneSerialDelete builder.
func (zsd *ZoneSerialDelete) Where(ps ...predicate.ZoneSerial) *ZoneSerialDelete {
	zsd.mutation.Where(ps...)
	return zsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (zsd *ZoneSerialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, zsd.sqlExec, zsd.mutation, zsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (zsd *ZoneSerialDelete) ExecX(ctx context.Context) int {
	n, err := zsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (zsd *ZoneSerialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(zoneserial.Table, sqlgraph.NewFieldSpec(zoneserial.FieldID, field.TypeInt))
	if ps := zsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, zsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	zsd.mutation.done = true
	return affected, err
}

// ZoneSerialDeleteOne is the builder for deleting a single ZoneSerial entity.
type ZoneSerialDeleteOne struct {
	zsd *ZoneSerialDelete
}

// Where appends a list predicates to the ZoneSerialDelete builder.
func (zsdo *ZoneSerialDeleteOne) Where(ps ...predicate.ZoneSerial) *ZoneSerialDeleteOne {
	zsdo.zsd.mutation.Where(ps...)
	return zsdo
}

// Exec executes the deletion query.
func (zsdo *ZoneSerialDeleteOne) Exec(ctx context.Context) error {
	n, err := zsdo.zsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{zoneserial.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (zsdo *ZoneSerialDeleteOne) ExecX(ctx context.Context) {
	if err := zsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
